# Copyright (c) 2026, Ampere Computing LLC
# SPDX-License-Identifier: BSD-3-Clause
#
# Assisted and/or generated by Codex:GPT-5

import evp

evp.require_transactions()


def probe_self(event):
    print(
        f"{event.name} parent_1={evp.transaction_parent(1)} "
        f"self_ancestor={evp.is_ancestor(1, 1)} "
        f"unrelated_99={evp.is_related(99, 1)}"
    )


def probe_parent_child(event):
    print(
        f"{event.name} parent_1={evp.transaction_parent(1)} "
        f"parent_2={evp.transaction_parent(2)} "
        f"root_2={evp.is_ancestor(1, 2)} "
        f"cycle_1_2={evp.is_ancestor(2, 1)} "
        f"related_1_2={evp.is_related(1, 2)}"
    )


def probe_cycle(event):
    print(
        f"{event.name} parent_3={evp.transaction_parent(3)} "
        f"parent_4={evp.transaction_parent(4)} "
        f"ancestor_4_3={evp.is_ancestor(4, 3)} "
        f"ancestor_3_4={evp.is_ancestor(3, 4)} "
        f"unrelated_99_4={evp.is_related(99, 4)}"
    )


evp.on("probe_self", probe_self)
evp.on("probe_parent_child", probe_parent_child)
evp.on("probe_cycle", probe_cycle)
