# Copyright (c) 2026, Ampere Computing LLC
# SPDX-License-Identifier: BSD-3-Clause
#
# Assisted and/or generated by Codex:GPT-5

import evp

evp.require_transactions()


def print_tx(event):
    txid = evp.event_txid(event)
    print(f"{event.name} txid={txid} parent={evp.transaction_parent(txid)}")


def print_probe(event):
    print(
        f"{event.name} parent_2={evp.transaction_parent(2)} "
        f"related_1_2={evp.is_related(1, 2)}"
    )


evp.on("end_transaction", print_tx)
evp.on("probe_after_end", print_probe)
