// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:GPT-5

#include "event_stream/mcp/query.h"
#include "event_stream/testing/build_event_stream.h"

#include <filesystem>
#include <fmt/format.h>
#include <map>
#include <string>

#include <gtest/gtest.h>

namespace mcp = perf_streams::event_stream::mcp;
namespace event_testing = perf_streams::event_stream::testing;
namespace fs = std::filesystem;

class EventStreamMCPTest : public ::testing::Test
{
protected:
    void SetUp() override { mcp::clear_cache(); }

    void TearDown() override { mcp::clear_cache(); }

    static std::string stream(const std::string& name)
    {
        return (fs::path(TEST_DIRECTORY) / "streams" / name).string();
    }

    static std::string stream_output(const std::string& name)
    {
        return (fs::path(TEST_OUTPUT_DIRECTORY) / name).string();
    }

    static std::string build_es(const std::string& name)
    {
        auto output_name = name.substr(0, name.rfind('.')) + ".es";
        return event_testing::build_es(stream(name), stream_output(output_name));
    }

    static std::map<std::string, uint64_t> metrics(const std::vector<mcp::Metric>& values)
    {
        std::map<std::string, uint64_t> result;
        for (const auto& metric : values)
            result[metric.name] = metric.value.as_uint();
        return result;
    }
};

TEST_F(EventStreamMCPTest, InspectExtractsMetadata)
{
    auto path = build_es("basic.in");
    auto result = mcp::inspect(path);

    EXPECT_EQ(result.stream_version, 4);
    EXPECT_EQ(result.event_count, 4);
    EXPECT_EQ(result.first_time, 100);
    EXPECT_EQ(result.last_time, 300);
    EXPECT_EQ(result.counts_by_definition["one"], 2);
    EXPECT_EQ(result.counts_by_definition["two"], 2);
    EXPECT_EQ(result.parameters.size(), 3);
}

TEST_F(EventStreamMCPTest, CountParamsAndSample)
{
    auto path = build_es("basic.in");

    mcp::CountOptions count_options;
    auto count_result = mcp::count(path, count_options);
    auto count_metrics = metrics(count_result.summary);
    EXPECT_EQ(count_metrics["one"], 2);
    EXPECT_EQ(count_metrics["two"], 2);

    count_options.events = {"one"};
    count_options.accumulate = {"one/data1"};
    auto accumulated = metrics(mcp::count(path, count_options).summary);
    EXPECT_EQ(accumulated["one"], 2);
    EXPECT_EQ(accumulated["one/data1"], 42);

    mcp::ParamsOptions params_options;
    params_options.all = true;
    EXPECT_EQ(mcp::params(path, params_options).parameters.size(), 3);

    mcp::SampleOptions sample_options;
    sample_options.events = {"two"};
    sample_options.limit = 1;
    auto sample = mcp::sample(path, sample_options);
    ASSERT_EQ(sample.events.size(), 1);
    EXPECT_EQ(sample.events.front().name, "two");
    EXPECT_TRUE(sample.truncated);
}

TEST_F(EventStreamMCPTest, CountExpandsEnumerations)
{
    auto path = build_es("enums.in");
    mcp::CountOptions options;
    options.events = {"access/state"};
    auto result = metrics(mcp::count(path, options).summary);

    EXPECT_EQ(result["access"], 3);
    EXPECT_EQ(result["access/state:MISS"], 1);
    EXPECT_EQ(result["access/state:HIT"], 2);
}

TEST_F(EventStreamMCPTest, LatencyMatchesRepresentativeEVPBehavior)
{
    auto path = build_es("latency.in");
    mcp::LatencyOptions options;
    options.events = {"a", "b"};
    auto result = metrics(mcp::latency(path, options).summary);

    EXPECT_EQ(result["a_b.sum_latency"], 350);
    EXPECT_EQ(result["a_b.count"], 2);
    EXPECT_EQ(result["a_b.min_latency"], 100);
    EXPECT_EQ(result["a_b.max_latency"], 250);
}

TEST_F(EventStreamMCPTest, RateBuildsIntervalHistogram)
{
    auto path = build_es("basic.in");
    mcp::RateOptions options;
    options.interval = "one";
    options.events = {"two"};
    auto result = metrics(mcp::rate(path, options).summary);

    EXPECT_EQ(result["two.rate.1"], 2);
}

TEST_F(EventStreamMCPTest, CacheInvalidatesWhenFileIdentityChanges)
{
    auto output = stream_output("cache.es");
    auto path = event_testing::build_es(stream("basic.in"), output);
    EXPECT_EQ(mcp::inspect(path).event_count, 4);
    EXPECT_EQ(mcp::cache_stats().streams, 1);

    event_testing::build_es(stream("single.in"), output);
    EXPECT_EQ(mcp::inspect(path).event_count, 1);
}
