[project]
name = "perf_streams"
version = "1.0.0"
description = 'Performance "Streams" are traces or collections of events or other messages, used for CPU performance simulation and analysis.'
readme = 'README.md'
license = {file = 'LICENSE.txt'}
authors = [
  {name = 'Aaron Lindsay', email = 'aaron@os.amperecomputing.com'},
  {name = 'Nick Kelly', email = 'kellynic@os.amperecomputing.com'},
]
requires-python = ">=3.12"
dependencies = [
    "capstone",
    "protobuf>=4.25.0",
]

[dependency-groups]
build = [
    "hatch"
]
test = [
    "coverage"
]
lint = [
    "ruff"
]
all = [
    {include-group = "build"},
    {include-group = "test"},
    {include-group = "lint"},
]

[build-system]
requires = ["scikit-build-core>=0.9"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.version = ">=3.24"
sdist.exclude = ["*.in", "*.xz", "*.es", "*.is", "*.ms", "*.bs"]

[tool.hatch.envs.hatch-test.scripts]
# Override the default 'run' script to use 'unittest'
run = "python -m unittest discover {args}"

[tool.ruff]
# Configure similar to black (except for line-length)
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
  "A",
  "ANN",
  "B",
  "C4",
  "D1",
  "D3",
  "D4",
  "E4",
  "E7",
  "E9",
  "ERA",
  "F",
  "FURB",
  "I",
  "INT",
  "N",
  "PGH004",
  "PIE",
  "PL",
  "PL",
  "PYI",
  "RET",
  "RUF",
  "SIM",
  "T20",
  "TID252",
  "UP",
]
ignore = [
  "COM812",
  "COM819",
  "D206",
  "D300",
  "E111",
  "E114",
  "E117",
  "E402",
  "E402",
  "E722",
  "E741",
  "F401",
  "F403",
  "ISC001",
  "ISC002",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "W191",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = ["F401"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"**/test*/*" = [
    "ANN",
    "B",
    "D",
    "F405",
    "PLR2004",
    "PLR0904"
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
suppress-none-returning = true
suppress-dummy-args = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

