# Copyright (c) 2026, Ampere Computing LLC
# SPDX-License-Identifier: BSD-3-Clause

"""Transaction extension for Python EventStream writers."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from perf_streams.event_stream import Event, EventType, EventValues, Transaction, ValueType

    class _TransactionWriterBase:
        """Type-only interface supplied by EventStreamWriterWith at runtime."""

        def __init__(self, filename: str) -> None:
            raise NotImplementedError

        def define_event(self, name: str, description: str) -> EventType:
            raise NotImplementedError

        def define_data(self, name: str, description: str) -> ValueType:
            raise NotImplementedError

        def _start_simulation_extensions(self) -> None:
            raise NotImplementedError

        def _assert_event_phase(self, operation: str) -> None:
            raise NotImplementedError

        def post_event(self, event_type: EventType, time: int, values: EventValues | None = None) -> Event:
            raise NotImplementedError

else:
    _TransactionWriterBase = object


def _transaction_type() -> type[Transaction]:
    return importlib.import_module("perf_streams.event_stream").Transaction


# Assisted and/or generated by Codex:gpt-5
class Transactions(_TransactionWriterBase):
    """EventStreamWriter extension adding transaction helpers."""

    requirements: tuple[type, ...] = ()

    def __init__(self, filename: str) -> None:
        """Initialize transaction writer state."""
        super().__init__(filename)
        self._next_txid = 0
        self.open_transactions: dict[int, Transaction] = {}  # keyed by txid

    def _create_transaction_definitions(self) -> None:
        transaction_type = _transaction_type()

        self._start_tx_event_id = self.define_event(
            transaction_type.DEFAULT_START_NAME, "Beginning of a new transaction"
        )
        self._end_tx_event_id = self.define_event(transaction_type.DEFAULT_END_NAME, "End of a transaction")
        self._txid_data_id = self.define_data(transaction_type.DEFAULT_TXID_NAME, "Transaction ID")
        self._parent_tx_data_id = self.define_data(transaction_type.DEFAULT_PARENT_NAME, "ID of parent transaction")

    def _start_simulation_extensions(self) -> None:
        """Define transaction records before events begin."""
        super()._start_simulation_extensions()
        self._create_transaction_definitions()

    def post_event(
        self,
        event_type: EventType,
        time: int,
        values: EventValues | None = None,
        transaction: Transaction | None = None,
    ) -> Event:
        """Post event, optionally associated with a transaction.

        Args:
            event_type: event definition type
            time: time of event
            values: values associated with event (dict of data definition type with value)
            transaction: associated transaction
        """
        if values is not None and not isinstance(values, dict):
            raise TypeError(f"values must be dict[ValueType, EventScalarValue], but was {type(values).__name__}")

        event_values = dict(values) if values else {}
        if transaction is not None:
            if transaction.closed:
                raise RuntimeError(f"Transaction {transaction.txid} has already ended")
            if transaction.txid not in self.open_transactions:
                raise RuntimeError(f"Transaction {transaction.txid} is not open")
            event_values[self._txid_data_id] = transaction.txid

        event = super().post_event(event_type, time=time, values=event_values)
        if transaction is not None:
            transaction.add_event(event)
        return event

    def begin_transaction(
        self,
        time: int,
        parent: Transaction | int | None = None,
        values: EventValues | None = None,
    ) -> Transaction:
        """Begin transaction.

        Args:
            time: time transaction begins
            parent: optional parent this transaction is associated with
            values: additional values on begin event
        """
        self._assert_event_phase("begin_transaction")

        if values is not None and not isinstance(values, dict):
            raise TypeError(f"values must be dict[ValueType, EventScalarValue], but was {type(values).__name__}")

        txid = self._next_txid
        self._next_txid += 1

        transaction_type = _transaction_type()
        transaction = transaction_type(txid)

        parent_txid = None
        if parent is not None:
            if isinstance(parent, transaction_type):
                parent_txid = parent.txid
                parent.add_child(transaction)
            else:
                parent_txid = int(parent)
                existing_parent = self.open_transactions.get(parent_txid)
                if existing_parent is not None:
                    existing_parent.add_child(transaction)

        start_values = dict(values) if values else {}
        start_values[self._txid_data_id] = txid

        if parent_txid is not None:
            start_values[self._parent_tx_data_id] = parent_txid

        self.open_transactions[txid] = transaction
        self.post_event(self._start_tx_event_id, time=time, values=start_values, transaction=transaction)
        return transaction

    def end_transaction(self, transaction: Transaction, time: int, values: EventValues | None = None) -> Event:
        """End transaction.

        Args:
            transaction: transaction to end
            time: time transaction ends
            values: additional values on end event
        """
        self._assert_event_phase("end_transaction")

        if values is not None and not isinstance(values, dict):
            raise TypeError(f"values must be dict[ValueType, EventScalarValue], but was {type(values).__name__}")

        end_values = dict(values) if values else {}
        end_values[self._txid_data_id] = transaction.txid
        end_event = self.post_event(self._end_tx_event_id, time=time, values=end_values, transaction=transaction)
        transaction.closed = True
        del self.open_transactions[transaction.txid]
        return end_event
