/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

// Assisted and/or generated by Codex:gpt-5

#include "event_stream/event.h"
#include "event_stream/event_stream.h"
#include "event_stream/event_stream_with.h"
#include "event_stream/transaction.h"

#include <cstdint>
#include <string>
#include <tuple>
#include <utility>

namespace perf_streams::event_stream::extensions {

using TransactionHandle = Transaction*;

template<EventStreamLayer Base>
class Transactions : public Base
{
public:
    using Base::Base;
    using Base::open_event;
    using Base::post_event;

    void post_event(EventType event_type, TimeType time, Transaction& transaction)
    {
        this->close_event(open_event(event_type, time, transaction));
    }

    EventHandle open_event(EventType event_type, TimeType time, Transaction& transaction)
    {
        auto* event = Base::open_event(event_type, time);
        this->add_uint_data(event, definition.txid, transaction.id());
        return event;
    }

    TransactionHandle begin_transaction(TimeType time, TransactionHandle parent = nullptr)
    {
        auto [event, transaction] = begin_transaction_with_data(time, parent);
        this->close_event(event);
        return transaction;
    }

    std::pair<EventHandle, TransactionHandle> begin_transaction_with_data(TimeType time,
                                                                          TransactionHandle parent = nullptr)
    {
        auto* transaction = new Transaction(definition.txid);
        auto* event = Base::open_event(definition.start_transaction, time);
        this->add_uint_data(event, definition.txid, transaction->id());
        if (parent)
            this->add_uint_data(event, definition.parent, parent->id());

        return {event, transaction};
    }

    void end_transaction(TransactionHandle transaction, TimeType time)
    {
        this->close_event(end_transaction_with_data(transaction, time));
    }

    EventHandle end_transaction_with_data(TransactionHandle transaction, TimeType time)
    {
        auto* event = Base::open_event(definition.end_transaction, time);
        this->add_uint_data(event, definition.txid, transaction->id());
        return event;
    }

    void start_simulation() override
    {
        definition.setup(*this);
        Base::start_simulation();
    }

private:
    struct TransactionDefinitions
    {
        EventType start_transaction;
        EventType end_transaction;
        DataType txid;
        DataType parent;

        void setup(EventStream& event_stream)
        {
            start_transaction = event_stream.define_event("start_transaction", "Beginning of a new transaction");
            end_transaction = event_stream.define_event("end_transaction", "End of a transaction");
            txid = event_stream.define_data("txid", "Transaction ID");
            parent = event_stream.define_data("parent", "ID of parent transaction");
        }
    } definition;
};

} // namespace perf_streams::event_stream::extensions

namespace perf_streams::event_stream {

template<>
struct EventStreamExtensionTraits<extensions::Transactions>
{
    using requirements = std::tuple<>;
};

} // namespace perf_streams::event_stream
