/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

#include "event_stream/event_stream.pb.h"

#include <cstdint>
#include <map>
#include <optional>

namespace perf_streams::event_stream::processor {

using event_stream_proto::Definition;
using event_stream_proto::Event;

// Assisted and/or generated by Codex:GPT-5
struct TransactionTracker
{
    void save_definition(const Definition& definition);
    void update(const Event& event);
    bool should_enable_event(uint32_t event_id) const;

    std::optional<uint64_t> event_txid(const Event& event) const;
    std::optional<uint64_t> transaction_parent(uint64_t txid) const;
    bool is_ancestor(uint64_t ancestor_txid, uint64_t descendant_txid) const;
    bool is_related(uint64_t txid_a, uint64_t txid_b) const;

private:
    std::optional<uint32_t> txid_definition_id;
    std::optional<uint32_t> parent_definition_id;
    std::optional<uint32_t> start_transaction_definition_id;
    std::optional<uint32_t> end_transaction_definition_id;
    std::map<uint64_t, uint64_t> transaction_parents;
};

} // namespace perf_streams::event_stream::processor
