/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

// Assisted and/or generated by Codex:gpt-5

#include "event_stream/event_stream.h"

#include <algorithm>
#include <concepts>
#include <cstdint>
#include <memory>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>

namespace perf_streams::event_stream {

template<typename T>
concept EventStreamLayer = std::derived_from<T, EventStream>;

template<template<typename> typename Extension>
struct EventStreamExtension
{};

template<template<typename> typename Extension>
struct EventStreamExtensionTraits
{
    using requirements = std::tuple<>;
};

namespace detail {

template<template<typename> typename... Extensions>
struct EventStreamExtensionList
{};

template<typename Requirement, template<typename> typename... Seen>
inline constexpr bool extension_was_seen_v = (std::is_same_v<Requirement, EventStreamExtension<Seen>> || ...);

template<typename Requirements, template<typename> typename... Seen>
struct RequirementsAreSatisfied;

template<template<typename> typename... Required, template<typename> typename... Seen>
struct RequirementsAreSatisfied<std::tuple<EventStreamExtension<Required>...>, Seen...>
    : std::bool_constant<(extension_was_seen_v<EventStreamExtension<Required>, Seen...> && ...)>
{};

template<typename Seen, template<typename> typename... Remaining>
struct EventStreamExtensionsAreValid;

template<template<typename> typename... Seen>
struct EventStreamExtensionsAreValid<EventStreamExtensionList<Seen...>> : std::true_type
{};

template<template<typename> typename... Seen,
         template<typename> typename Current,
         template<typename> typename... Remaining>
struct EventStreamExtensionsAreValid<EventStreamExtensionList<Seen...>, Current, Remaining...>
    : std::bool_constant<
          RequirementsAreSatisfied<typename EventStreamExtensionTraits<Current>::requirements, Seen...>::value
          && EventStreamExtensionsAreValid<EventStreamExtensionList<Seen..., Current>, Remaining...>::value>
{};

template<typename Base, template<typename> typename... Extensions>
struct ApplyEventStreamExtensions;

template<typename Base>
struct ApplyEventStreamExtensions<Base>
{
    using type = Base;
};

template<typename Base, template<typename> typename Current, template<typename> typename... Remaining>
struct ApplyEventStreamExtensions<Base, Current, Remaining...>
{
    using type = typename ApplyEventStreamExtensions<Current<Base>, Remaining...>::type;
};

} // namespace detail

template<template<typename> typename... Extensions>
inline constexpr bool event_stream_extensions_valid_v =
    detail::EventStreamExtensionsAreValid<detail::EventStreamExtensionList<>, Extensions...>::value;

class EventStreamForwarder : public EventStream
{
public:
    explicit EventStreamForwarder(EventStream& event_stream) : event_stream(&event_stream)
    {
        share_state(event_stream);
    }

    explicit EventStreamForwarder(std::unique_ptr<EventStream>&& event_stream)
        : owned_event_stream(std::move(event_stream)), event_stream(owned_event_stream.get())
    {
        share_state(*this->event_stream);
    }

    void post_event(EventType event_type, TimeType time) override
    {
        event_stream->post_event(event_type, time);
        sync_catch_up_indexes();
    }
    EventHandle open_event(EventType event_type, TimeType time) override
    {
        auto* event = event_stream->open_event(event_type, time);
        sync_catch_up_indexes();
        return event;
    }
    void close_event(EventHandle event) override
    {
        event_stream->close_event(event);
        sync_catch_up_indexes();
    }

    void add_int_data(EventHandle event, DataType event_data_type, std::int64_t value) override
    {
        event_stream->add_int_data(event, event_data_type, value);
        sync_catch_up_indexes();
    }
    void add_uint_data(EventHandle event, DataType event_data_type, std::uint64_t value) override
    {
        event_stream->add_uint_data(event, event_data_type, value);
        sync_catch_up_indexes();
    }
    void add_string_data(EventHandle event, DataType event_data_type, const std::string& value) override
    {
        event_stream->add_string_data(event, event_data_type, value);
        sync_catch_up_indexes();
    }

    void set_bool_parameter(const std::string& name, const std::string& description, bool value) override
    {
        event_stream->set_bool_parameter(name, description, value);
        sync_catch_up_indexes();
    }
    void set_int_parameter(const std::string& name, const std::string& description, std::int64_t value) override
    {
        event_stream->set_int_parameter(name, description, value);
        sync_catch_up_indexes();
    }
    void set_uint_parameter(const std::string& name, const std::string& description, std::uint64_t value) override
    {
        event_stream->set_uint_parameter(name, description, value);
        sync_catch_up_indexes();
    }
    void set_double_parameter(const std::string& name, const std::string& description, double value) override
    {
        event_stream->set_double_parameter(name, description, value);
        sync_catch_up_indexes();
    }
    void set_string_parameter(const std::string& name,
                              const std::string& description,
                              const std::string& value) override
    {
        event_stream->set_string_parameter(name, description, value);
        sync_catch_up_indexes();
    }
    void set_json_parameter(const std::string& name, const std::string& description, const std::string& value) override
    {
        event_stream->set_json_parameter(name, description, value);
        sync_catch_up_indexes();
    }

    void start_simulation() override
    {
        event_stream->start_simulation();
        sync_catch_up_indexes();
    }
    void enable() override { event_stream->enable(); }
    void disable() override { event_stream->disable(); }
    bool is_enabled() override { return event_stream->is_enabled(); }

protected:
    void finalize_event_definition(EventType event_type,
                                   const std::string& name,
                                   const std::string& description) override
    {
        event_stream->finalize_event_definition(event_type, name, description);
        event_stream->definition_index = std::max(event_stream->definition_index, static_cast<size_t>(event_type));
    }
    void finalize_data_definition(DataType data_type, const std::string& name, const std::string& description) override
    {
        event_stream->finalize_data_definition(data_type, name, description);
        event_stream->definition_index = std::max(event_stream->definition_index, static_cast<size_t>(data_type));
    }
    void finalize_data_definition(DataType data_type,
                                  const std::string& name,
                                  const std::string& description,
                                  EnumType enumeration) override
    {
        event_stream->finalize_data_definition(data_type, name, description, enumeration);
        event_stream->definition_index = std::max(event_stream->definition_index, static_cast<size_t>(data_type));
    }
    void finalize_enum_definition(EnumType enum_type, const EnumMappingType& enumerations) override
    {
        event_stream->finalize_enum_definition(enum_type, enumerations);
        event_stream->enumeration_index = std::max(event_stream->enumeration_index, static_cast<size_t>(enum_type) + 1);
    }

private:
    void sync_catch_up_indexes()
    {
        definition_index = event_stream->definition_index;
        enumeration_index = event_stream->enumeration_index;
    }

    void share_state(EventStream& event_stream)
    {
        owned_definitions.reset();
        definitions = event_stream.definitions;
        definition_index = event_stream.definition_index;

        owned_enumerations.reset();
        enumerations = event_stream.enumerations;
        enumeration_index = event_stream.enumeration_index;
    }

    std::unique_ptr<EventStream> owned_event_stream;
    EventStream* event_stream{nullptr};
};

template<template<typename> typename... Extensions>
class EventStreamWith : public detail::ApplyEventStreamExtensions<EventStreamForwarder, Extensions...>::type
{
    using Base = typename detail::ApplyEventStreamExtensions<EventStreamForwarder, Extensions...>::type;

    static_assert(event_stream_extensions_valid_v<Extensions...>,
                  "EventStreamWith extension requirements must be listed before the extension requiring them");

public:
    using Base::Base;
};

} // namespace perf_streams::event_stream
