from collections.abc import Callable
from enum import IntEnum
from typing import Any

class Event:
    name: str
    time: int
    data: dict[str, int | str]

enums: dict[str, type[IntEnum]]

def on(event_spec: str, callback: Callable[[Event], None]) -> None: ...
def collect(callback: Callable[[int], dict[str, int]]) -> None: ...
def end_simulation(callback: Callable[[], None]) -> None: ...
def has_definition(name: str) -> bool: ...
def get_parameter(name: str) -> Any: ...
