from collections.abc import Callable

def on(event: str, callback: Callable[..., None]) -> None: ...
def collect(callback: Callable[[int], dict[str, int]]) -> None: ...
def end_simulation(callback: Callable[[], None]) -> None: ...
