/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Assisted and/or generated by Codex:GPT-5
 */

#pragma once

#include <fmt/format.h>
#include <string>
#include <string_view>

namespace perf_streams::event_stream::processor::plugins {

inline std::string count_data_metric_name(std::string_view event_name, std::string_view data_name)
{
    return fmt::format("{}/{}", event_name, data_name);
}

inline std::string count_factor_metric_suffix(std::string_view factor_name, std::string_view factor_value)
{
    return fmt::format("/{}:{}", factor_name, factor_value);
}

inline std::string count_factor_metric_name(std::string_view event_name,
                                            std::string_view factor_name,
                                            std::string_view factor_value)
{
    return fmt::format("{}{}", event_name, count_factor_metric_suffix(factor_name, factor_value));
}

inline std::string count_empty_factor_metric_name(std::string_view event_name)
{
    return fmt::format("{}/", event_name);
}

} // namespace perf_streams::event_stream::processor::plugins
