// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:gpt-5

#pragma once

#include "event_stream/processor/plugin.h"
#include "event_stream/processor/utils.h"

#include <cstdint>
#include <fmt/format.h>
#include <limits>
#include <string>
#include <utility>

namespace perf_streams::event_stream::processor {

class IntervalHistogramPlugin : public Plugin
{
public:
    enum class Interval {
        None,
        Time,
        Event,
    };

    explicit IntervalHistogramPlugin(ProcessorIfc& proc_ifc) : Plugin{proc_ifc} {}

    void end_simulation() override { ended = true; }

protected:
    template<typename T>
    void configure_interval(const std::string& interval,
                            const std::string& plugin_name,
                            void (T::*event_action)(Counter*, const Event&),
                            void (T::*time_action)(uint64_t current_time, uint64_t expiry))
    {
        if (is_time_spec(interval)) {
            time_interval_value = parse_time_spec(interval);
            if (time_interval_value == 0)
                throw PluginError{fmt::format("{} interval must be greater than zero", plugin_name)};

            interval_type = Interval::Time;
            at_every(interval, time_action);
        } else {
            interval_type = Interval::Event;
            on_every(interval, event_action);
        }
    }

    template<typename Action>
    void for_each_time_boundary(uint64_t current_time, uint64_t expiry, Action&& action) const
    {
        for (auto boundary = expiry; boundary <= current_time;) {
            action(boundary);

            if (std::numeric_limits<uint64_t>::max() - boundary < time_interval_value)
                break;
            boundary += time_interval_value;
        }
    }

    uint64_t empty_time_boundaries_after(uint64_t current_time, uint64_t expiry) const
    {
        return (current_time / time_interval_value) - (expiry / time_interval_value);
    }

    template<typename Action>
    void finish_final_interval(Action&& action)
    {
        if (ended && interval_type != Interval::None)
            action();
    }

    void set_factored_metrics(bool factored) { factored_metrics = factored; }

    bool interval_configured() const { return interval_type != Interval::None; }

    template<typename Bucket>
    std::string format_histogram_bucket(const std::string& metric_prefix,
                                        const std::string& dotted_component,
                                        const std::string& factored_component,
                                        Bucket&& bucket) const
    {
        if (factored_metrics)
            return fmt::format("{}/{}:{}", metric_prefix, factored_component, std::forward<Bucket>(bucket));
        if (dotted_component.empty())
            return fmt::format("{}.{}", metric_prefix, std::forward<Bucket>(bucket));
        return fmt::format("{}.{}.{}", metric_prefix, dotted_component, std::forward<Bucket>(bucket));
    }

private:
    bool ended{false};
    bool factored_metrics{false};
    Interval interval_type{Interval::None};
    uint64_t time_interval_value{0};
};

} // namespace perf_streams::event_stream::processor
