/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Assisted and/or generated by Codex:GPT-5
 */

#pragma once

#include "event_stream/processor/bounds.h"
#include "event_stream/processor/plugins/rate.h"
#include "event_stream/processor/utils.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <fmt/format.h>
#include <functional>
#include <limits>
#include <map>
#include <numeric>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace perf_streams::event_stream::processor::plugins {

struct TimeCount
{
    uint64_t time{0};
    uint64_t count{0};
};

template<typename StdevValue = double>
struct BasicLatencyHist
{
    StdevValue stdev{0.0};
    uint64_t min_latency{std::numeric_limits<uint64_t>::max()};
    std::vector<uint64_t> max_latencies;
    std::map<uint64_t, uint64_t> latency_counts;
};

using LatencyHist = BasicLatencyHist<double>;
using LatencyInfo = std::vector<TimeCount>;
using LatencyHistInfo = std::vector<LatencyHist>;

struct LatencyTracker
{
    LatencyTracker(uint64_t start_time, size_t num_events)
        : time_per_event(num_events), last_event_time{start_time}, last_event_idx{-1}
    {
    }

    LatencyInfo time_per_event;
    uint64_t last_event_time{0};
    int last_event_idx{-1};
    bool saw_start_event{false};
};

inline std::string build_latency_name(const std::vector<std::string>& events)
{
    if (events.empty())
        return "";

    std::stringstream name;
    auto prefix = extract_prefix(events.front()).first;
    bool first = true;
    for (auto event : events) {
        if (!first) {
            name << "_";
            auto [event_prefix, event_name] = extract_prefix(event);
            if (event_prefix == prefix) {
                name << event_name;
            } else {
                std::ranges::replace(event, '.', '_');
                name << event;
            }
        } else {
            name << event;
        }
        first = false;
    }
    return name.str();
}

inline void record_latency(LatencyTracker& tracker, uint64_t now, int idx)
{
    if (tracker.last_event_idx >= 0) {
        auto latency = now - tracker.last_event_time;
        auto& time_count = tracker.time_per_event[tracker.last_event_idx];
        time_count.time += latency;
        time_count.count += 1;
    }

    tracker.last_event_time = now;
    tracker.last_event_idx = idx;
    if (idx == 0)
        tracker.saw_start_event = true;
}

template<typename Hist>
inline void track_max_latency(Hist& hist_info, uint64_t latency, size_t max_latencies)
{
    if (max_latencies == 0)
        return;
    if (hist_info.max_latencies.size() >= max_latencies && latency <= hist_info.max_latencies.back())
        return;

    if (hist_info.max_latencies.size() >= max_latencies)
        hist_info.max_latencies.pop_back();

    hist_info.max_latencies.push_back(latency);
    std::sort(hist_info.max_latencies.begin(), hist_info.max_latencies.end(), std::greater<uint64_t>());
}

template<typename HistInfo>
inline void aggregate_latency(const LatencyTracker& tracker,
                              LatencyInfo& aggregated_info,
                              HistInfo& aggregated_hist_info,
                              const FactorBounds* histogram_bounds,
                              bool histogram,
                              size_t max_latencies = 10)
{
    if (!tracker.saw_start_event || tracker.last_event_idx < 0)
        return;

    for (size_t idx = 0; idx < tracker.time_per_event.size(); ++idx) {
        const auto& tracker_entry = tracker.time_per_event[idx];
        auto& info = aggregated_info[idx];
        auto latency = tracker_entry.time;
        info.time += tracker_entry.time;
        info.count += tracker_entry.count;

        if (!latency)
            continue;

        auto& hist_info = aggregated_hist_info[idx];
        if (histogram) {
            auto bucket = histogram_bounds ? histogram_bounds->adjust(latency) : latency;
            ++hist_info.latency_counts[bucket];
        }

        track_max_latency(hist_info, latency, max_latencies);
        hist_info.min_latency = std::min(hist_info.min_latency, latency);
        if (info.count > 1)
            hist_info.stdev =
                std::sqrt((info.time * info.time + (info.time * info.time) / info.count) / (info.count - 1));
    }
}

template<typename Metrics, typename Value>
void assign_metric(Metrics& metrics, const std::string& name, Value value)
{
    metrics[name] = value;
}

inline std::string histogram_metric_name_for_latency(std::string_view event_name,
                                                     std::string_view suffix,
                                                     uint64_t bucket,
                                                     bool factored)
{
    return histogram_metric_name(event_name, suffix, bucket, factored);
}

template<typename Metrics, typename Hist>
void assign_latency_metrics(Metrics& metrics,
                            std::string_view name,
                            const TimeCount& info,
                            const Hist& hist_info,
                            std::string_view histogram_metric_name = {},
                            bool factored_histogram = false,
                            std::string_view event = {},
                            bool emit_histogram = false)
{
    auto prefix = event.empty() ? std::string{name} : fmt::format("{}.{}", name, event);

    assign_metric(metrics, fmt::format("{}.sum_latency", prefix), info.time);
    assign_metric(metrics, fmt::format("{}.count", prefix), info.count);
    assign_metric(metrics, fmt::format("{}.stdev", prefix), hist_info.stdev);

    if (!hist_info.max_latencies.empty()) {
        assign_metric(metrics, fmt::format("{}.max_latency", prefix), hist_info.max_latencies.front());
        assign_metric(metrics, fmt::format("{}.min_latency", prefix), hist_info.min_latency);
        auto max_sum = std::accumulate(hist_info.max_latencies.begin(), hist_info.max_latencies.end(), uint64_t{0});
        assign_metric(metrics,
                      fmt::format("{}.max_avg_latency", prefix),
                      static_cast<uint64_t>(max_sum / hist_info.max_latencies.size()));
    }

    if (emit_histogram) {
        for (const auto& [latency, count] : hist_info.latency_counts) {
            auto metric = histogram_metric_name_for_latency(prefix, histogram_metric_name, latency, factored_histogram);
            assign_metric(metrics, metric, count);
        }
    }
}

} // namespace perf_streams::event_stream::processor::plugins
