// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:gpt-5

#include "event_stream/processor/args.h"
#include "event_stream/processor/counter.h"
#include "event_stream/processor/metric_table.h"
#include "event_stream/processor/plugin.h"
#include "event_stream/processor/processor_ifc.h"
#include "event_stream/processor/utils.h"

#include <algorithm>
#include <cstdint>
#include <fmt/format.h>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace perf_streams::event_stream::processor {

EVP_PLUGIN(Occupancy, "occupancy", "Accumulate occupancy-duration histograms")
{
public:
    Occupancy(ProcessorIfc & proc_ifc, Args & args);

    static void help(int argc, const char** argv);
    void allocate(Counter * counter, const Event& event);
    void deallocate(Counter * counter, const Event& event);
    void collect_within_time(uint64_t current_time, uint64_t expiry);
    void collect(MetricSeries & metrics, uint64_t trigger_time) override;
    std::set<Phase> phases() const override
    {
        return {Phase::EVENTS};
    }

private:
    std::string metric_prefix{"occupancy"};
    bool factored{false};

    uint64_t occupancy{0};
    uint64_t last_time{0};
    bool initialized{false};
    std::map<uint64_t, uint64_t> histogram;

    void initialize_time();
    void accumulate_until(uint64_t time);
    void update_occupancy(const Event& event, int delta);
    std::string bucket_name(uint64_t bucket) const;
};

Occupancy::Occupancy(ProcessorIfc& proc_ifc, Args& args) : Plugin{proc_ifc}
{
    std::vector<std::string> events;

    while (args) {
        std::string arg;

        if (args.pop("-n|--name", metric_prefix)) {
        } else if (args.pop("--factored")) {
            factored = true;
        } else if (args.pop(arg)) {
            events.emplace_back(arg);
        } else {
            break;
        }
    }

    args.done();

    if (events.size() == 3) {
        if (!is_time_spec(events[0]))
            throw PluginError{"occupancy interval must be a time value"};

        if (parse_time_spec(events[0]) == 0)
            throw PluginError{"occupancy interval must be greater than zero"};

        at_every(events[0], &Occupancy::collect_within_time);
        events.erase(events.begin());
    }

    if (events.size() != 2)
        throw PluginError{"occupancy expects exactly two events: [<time interval>] <alloc event> <dealloc event>"};

    on_every(events[0], &Occupancy::allocate);
    on_every(events[1], &Occupancy::deallocate);
}

void Occupancy::help(int argc, const char** argv)
{
    print_help(argv[0],
               "occupancy",
               "[-n|--name <name>] [--factored] [<time interval>] <alloc event> <dealloc event>",
               R"(Arguments:

    <time interval>    Optional time interval with ps/ns/us/ms/s suffix support, like +rate.
    <alloc event>       Event that increments occupancy.
    <dealloc event>     Event that decrements occupancy.
    -n, --name <name>   Metric prefix for occupancy-duration buckets.
    --factored          Emit buckets as factored metrics instead of dotted suffixes.
    --help, -h          This help message.
)");
}

void Occupancy::initialize_time()
{
    if (initialized)
        return;

    last_time = get_first_event_time();
    histogram[occupancy] += 0;
    initialized = true;
}

void Occupancy::accumulate_until(uint64_t time)
{
    initialize_time();

    auto duration = time > last_time ? time - last_time : 0;
    histogram[occupancy] += duration;
    last_time = std::max(last_time, time);
}

void Occupancy::update_occupancy(const Event& event, int delta)
{
    accumulate_until(event.time());

    if (delta > 0) {
        occupancy += static_cast<uint64_t>(delta);
    } else if (auto decrement = static_cast<uint64_t>(-delta); decrement > occupancy) {
        occupancy = 0;
    } else {
        occupancy -= decrement;
    }

    histogram[occupancy] += 0;
}

void Occupancy::allocate(Counter* counter, const Event& event)
{
    update_occupancy(event, 1);
}

void Occupancy::deallocate(Counter* counter, const Event& event)
{
    update_occupancy(event, -1);
}

void Occupancy::collect_within_time(uint64_t, uint64_t expiry)
{
    accumulate_until(expiry);
}

std::string Occupancy::bucket_name(uint64_t bucket) const
{
    if (factored)
        return fmt::format("{}/occupancy:{}", metric_prefix, bucket);
    return fmt::format("{}.{}", metric_prefix, bucket);
}

void Occupancy::collect(MetricSeries& metrics, uint64_t trigger_time)
{
    accumulate_until(trigger_time);

    for (const auto& [bucket, duration] : histogram)
        metrics[bucket_name(bucket)] = duration;
}

} // namespace perf_streams::event_stream::processor
