// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:gpt-5

#include "event_stream/processor/args.h"
#include "event_stream/processor/counter.h"
#include "event_stream/processor/metric_table.h"
#include "event_stream/processor/plugins/interval_histogram.h"
#include "event_stream/processor/processor_ifc.h"

#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

namespace perf_streams::event_stream::processor {

EVP_PLUGIN_FROM(Occupancy, "occupancy", "Accumulate occupancy-duration histograms", IntervalHistogramPlugin)
{
public:
    Occupancy(ProcessorIfc & proc_ifc, Args & args);

    static void help(int argc, const char** argv);
    void allocate(Counter * counter, const Event& event);
    void deallocate(Counter * counter, const Event& event);
    void collect_within_event(Counter * counter, const Event& event);
    void collect_within_time(uint64_t current_time, uint64_t expiry);
    void collect(MetricSeries & metrics, uint64_t trigger_time) override;
    std::set<Phase> phases() const override
    {
        return {Phase::COUNTERS};
    }

private:
    std::string metric_prefix{"occupancy"};

    uint64_t occupancy{0};
    uint64_t last_time{0};
    bool initialized{false};
    std::map<uint64_t, uint64_t> histogram;

    void initialize_time();
    void accumulate_until(uint64_t time);
    void finish_interval(uint64_t time);
    void update_occupancy(const Event& event, int delta);
    std::string bucket_name(uint64_t bucket) const;
};

Occupancy::Occupancy(ProcessorIfc& proc_ifc, Args& args) : IntervalHistogramPlugin{proc_ifc}
{
    std::vector<std::string> events;

    while (args) {
        std::string arg;

        if (args.pop("-n|--name", metric_prefix)) {
        } else if (args.pop("--factored")) {
            set_factored_metrics(true);
        } else if (args.pop(arg)) {
            events.emplace_back(arg);
        } else {
            break;
        }
    }

    args.done();

    if (events.size() == 3) {
        configure_interval(events[0], "occupancy", &Occupancy::collect_within_event, &Occupancy::collect_within_time);
        events.erase(events.begin());
    }

    if (events.size() != 2)
        throw PluginError{"occupancy expects exactly two events: [<time interval>] <alloc event> <dealloc event>"};

    on_every(events[0], &Occupancy::allocate);
    on_every(events[1], &Occupancy::deallocate);
}

void Occupancy::help(int argc, const char** argv)
{
    print_help(argv[0],
               "occupancy",
               "[-n|--name <name>] [--factored] [<interval>] <alloc event> <dealloc event>",
               R"(Arguments:

    <interval>         Optional time interval with ps/ns/us/ms/s suffix support, or event to
                       consider as an interval boundary, like +rate. When supplied, the
                       histogram buckets are occupancy samples at interval boundaries and
                       values are sample counts.
    <alloc event>       Event that increments occupancy.
    <dealloc event>     Event that decrements occupancy.
    -n, --name <name>   Metric prefix for occupancy-duration buckets.
    --factored          Emit buckets as factored metrics instead of dotted suffixes.
    --help, -h          This help message.
)");
}

void Occupancy::initialize_time()
{
    if (initialized)
        return;

    last_time = get_first_event_time();
    if (!interval_configured())
        histogram.try_emplace(occupancy, 0);
    initialized = true;
}

void Occupancy::accumulate_until(uint64_t time)
{
    initialize_time();

    auto duration = time > last_time ? time - last_time : 0;
    if (!interval_configured())
        histogram[occupancy] += duration;
    last_time = std::max(last_time, time);
}

void Occupancy::finish_interval(uint64_t time)
{
    initialize_time();
    ++histogram[occupancy];
    mark_interval_update(time);
}

void Occupancy::update_occupancy(const Event& event, int delta)
{
    accumulate_until(event.time());

    if (delta > 0) {
        occupancy += static_cast<uint64_t>(delta);
    } else if (auto decrement = static_cast<uint64_t>(-delta); decrement > occupancy) {
        occupancy = 0;
    } else {
        occupancy -= decrement;
    }

    if (!interval_configured())
        histogram.try_emplace(occupancy, 0);
}

void Occupancy::allocate(Counter* counter, const Event& event)
{
    update_occupancy(event, 1);
}

void Occupancy::deallocate(Counter* counter, const Event& event)
{
    update_occupancy(event, -1);
}

void Occupancy::collect_within_event(Counter* counter, const Event& event)
{
    accumulate_until(event.time());
    finish_interval(event.time());
}

void Occupancy::collect_within_time(uint64_t current_time, uint64_t expiry)
{
    for_each_time_boundary(current_time, expiry, [this](uint64_t boundary) {
        accumulate_until(boundary);
        finish_interval(boundary);
    });
}

std::string Occupancy::bucket_name(uint64_t bucket) const
{
    return format_histogram_bucket(metric_prefix, "", "occupancy", bucket);
}

void Occupancy::collect(MetricSeries& metrics, uint64_t trigger_time)
{
    accumulate_until(trigger_time);
    finish_final_interval(trigger_time, [this, trigger_time] { finish_interval(trigger_time); });

    for (const auto& [bucket, duration] : histogram)
        metrics[bucket_name(bucket)] = duration;
}

} // namespace perf_streams::event_stream::processor
