/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Assisted and/or generated by Codex:GPT-5
 */

#pragma once

#include <fmt/format.h>
#include <string>
#include <string_view>

namespace perf_streams::event_stream::processor::plugins {

template<typename Bucket>
inline std::string histogram_metric_name(std::string_view event_name,
                                         std::string_view suffix,
                                         Bucket bucket,
                                         bool factored)
{
    return factored ? fmt::format("{}/{}:{}", event_name, suffix, bucket)
                    : fmt::format("{}.{}.{}", event_name, suffix, bucket);
}

} // namespace perf_streams::event_stream::processor::plugins
