// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause

// Assisted and/or generated by Codex:gpt-5

#include "event_stream/event_stream_with.h"
#include "event_stream/testing/test.h"

#include <tuple>

#include <gtest/gtest.h>

using perf_streams::event_stream::EventDefinition;
using perf_streams::event_stream::EventStreamExtension;
using perf_streams::event_stream::EventStreamLayer;
using perf_streams::event_stream::EventStreamWith;

struct EventStreamExtensionTest : public perf_streams::event_stream::testing::EventStreamTest
{};

template<EventStreamLayer Base>
class TestExtensionA : public Base
{
public:
    using Base::Base;

    int extension_value() const { return 41; }
};

template<EventStreamLayer Base>
class TestExtensionB : public Base
{
public:
    using Base::Base;

    int dependent_value() const { return this->extension_value() + 1; }
};

namespace perf_streams::event_stream::extensions {

template<>
struct EventStreamExtensionTraits<TestExtensionB>
{
    using requirements = std::tuple<EventStreamExtension<TestExtensionA>>;
};

} // namespace perf_streams::event_stream::extensions

static_assert(perf_streams::event_stream::event_stream_extensions_valid_v<TestExtensionA, TestExtensionB>);
static_assert(!perf_streams::event_stream::event_stream_extensions_valid_v<TestExtensionB>);

TEST_F(EventStreamExtensionTest, ForwarderUsesWrappedDefinitions)
{
    EventStreamWith<> stream(*event_stream);
    EventDefinition event(stream, "wrapped_event", "wrapped event");
    stream.start_simulation();

    EXPECT_CALL(*event_announcer, post_event("wrapped_event", 7));

    event.at(7);
}

TEST_F(EventStreamExtensionTest, ExtensionsCanBuildOnEarlierExtensions)
{
    EventStreamWith<TestExtensionA, TestExtensionB> const stream(*event_stream);

    EXPECT_EQ(stream.dependent_value(), 42);
}
