add_cpp_test(test_event_stream_viewer SOURCES test_viewer.cc)
target_link_libraries(test_event_stream_viewer testing)
target_compile_definitions(test_event_stream_viewer PRIVATE EVENT_STREAM_VIEWER_BIN="$<TARGET_FILE:es_viewer>")
add_dependencies(test_event_stream_viewer es_viewer)

add_cpp_test(test_gem5_o3pipeview_to_es SOURCES test_gem5_o3pipeview_to_es.cc)
target_link_libraries(test_gem5_o3pipeview_to_es testing)
target_compile_definitions(test_gem5_o3pipeview_to_es PRIVATE EVENT_STREAM_VIEWER_BIN="$<TARGET_FILE:es_viewer>")
target_compile_definitions(test_gem5_o3pipeview_to_es PRIVATE O3PIPEVIEW_TO_ES_BIN="$<TARGET_FILE:o3pipeview_to_es>")
add_dependencies(test_gem5_o3pipeview_to_es es_viewer o3pipeview_to_es)
