// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
// Assisted and/or generated by Codex:GPT-5

#include "event_stream/event_stream_proto.h"

#include <boost/program_options.hpp>
#include <cstddef>
#include <cstdint>
#include <fmt/base.h>
#include <fmt/format.h>
#include <fstream>
#include <ios>
#include <iostream>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

namespace po = boost::program_options;

namespace {

using perf_streams::event_stream::DataType;
using perf_streams::event_stream::EventHandle;
using perf_streams::event_stream::EventStreamProto;
using perf_streams::event_stream::EventType;
using perf_streams::protobuf_utils::CompressionType;

struct InstructionRecord
{
    std::uint64_t fetch_time{0};
    std::uint64_t pc{0};
    std::uint64_t micro_pc{0};
    std::uint64_t seq_num{0};
    std::string disasm;
    std::unordered_map<std::string, std::uint64_t> stage_times;
    std::vector<std::string> stage_order;

    void record_stage(const std::string& stage, std::uint64_t time)
    {
        if (!stage_times.contains(stage))
            stage_order.push_back(stage);
        stage_times[stage] = time;
    }

    std::optional<std::uint64_t> stage_time(const std::string& stage) const
    {
        if (auto it = stage_times.find(stage); it != stage_times.end())
            return it->second;
        return std::nullopt;
    }
};

struct Definitions
{
    EventType start_transaction;
    EventType end_transaction;
    DataType txid;
    DataType seq_num;
    DataType pc;
    DataType micro_pc;
    DataType disasm;
    std::unordered_map<std::string, EventType> stage_events;
};

[[noreturn]] void parse_error(std::size_t line_number, std::string_view message)
{
    throw std::runtime_error(fmt::format("line {}: {}", line_number, message));
}

std::uint64_t parse_u64(std::string_view token, std::size_t line_number, std::string_view field_name)
{
    if (token.empty())
        parse_error(line_number, fmt::format("missing {}", field_name));

    std::size_t consumed = 0;
    std::uint64_t value = 0;
    try {
        value = std::stoull(std::string(token), &consumed, 0);
    } catch (const std::exception&) {
        parse_error(line_number, fmt::format("invalid {} '{}'", field_name, token));
    }

    if (consumed != token.size())
        parse_error(line_number, fmt::format("invalid {} '{}'", field_name, token));

    return value;
}

std::vector<std::string_view> split_all(std::string_view line)
{
    std::vector<std::string_view> parts;
    std::size_t start = 0;
    while (true) {
        std::size_t pos = line.find(':', start);
        if (pos == std::string_view::npos) {
            parts.push_back(line.substr(start));
            return parts;
        }

        parts.push_back(line.substr(start, pos - start));
        start = pos + 1;
    }
}

InstructionRecord parse_fetch_line(std::string_view line, std::size_t line_number)
{
    std::string_view fields[6];
    std::size_t start = 0;
    for (auto& field : fields) {
        std::size_t pos = line.find(':', start);
        if (pos == std::string_view::npos)
            parse_error(line_number, "malformed fetch line");
        field = line.substr(start, pos - start);
        start = pos + 1;
    }

    if (fields[0] != "O3PipeView")
        parse_error(line_number, "malformed fetch line");
    if (fields[1] != "fetch")
        parse_error(line_number, "expected fetch line");

    InstructionRecord record;
    record.fetch_time = parse_u64(fields[2], line_number, "fetch time");
    record.pc = parse_u64(fields[3], line_number, "pc");
    record.micro_pc = parse_u64(fields[4], line_number, "micro_pc");
    record.seq_num = parse_u64(fields[5], line_number, "seq_num");
    record.disasm = std::string(line.substr(start));
    record.record_stage("fetch", record.fetch_time);
    return record;
}

void parse_stage_line(std::string_view line,
                      std::size_t line_number,
                      InstructionRecord& instruction,
                      Definitions& definitions,
                      EventStreamProto& stream)
{
    auto fields = split_all(line);
    if (fields.size() < 3 || fields[0] != "O3PipeView")
        parse_error(line_number, "malformed stage line");
    if (((fields.size() - 1) % 2) != 0)
        parse_error(line_number, "stage line must contain stage/time pairs");

    for (std::size_t i = 1; i < fields.size(); i += 2) {
        auto stage = fields[i];
        if (stage.empty())
            parse_error(line_number, "empty stage name");

        auto stage_name = std::string(stage);
        instruction.record_stage(stage_name, parse_u64(fields[i + 1], line_number, stage_name + " time"));
        if (!definitions.stage_events.contains(stage_name)) {
            definitions.stage_events.emplace(
                stage_name, stream.define_event(stage_name, fmt::format("gem5 O3PipeView stage '{}'", stage_name)));
        }
    }
}

CompressionType parse_compression(const std::string& value)
{
    if (value == "none")
        return CompressionType::NONE;
    if (value == "xz")
        return CompressionType::XZ;
    throw std::runtime_error(fmt::format("unsupported compression '{}': expected auto, none, or xz", value));
}

std::optional<CompressionType> resolve_compression(const std::string& output_path, const std::string& value)
{
    if (value == "auto") {
        if (output_path == "-")
            return CompressionType::NONE;
        return std::nullopt;
    }

    return parse_compression(value);
}

void add_stage_metadata(EventStreamProto& stream,
                        EventHandle event,
                        const Definitions& definitions,
                        const InstructionRecord& instruction)
{
    stream.add_uint_data(event, definitions.txid, instruction.seq_num);
    stream.add_uint_data(event, definitions.seq_num, instruction.seq_num);
    stream.add_uint_data(event, definitions.pc, instruction.pc);
    stream.add_uint_data(event, definitions.micro_pc, instruction.micro_pc);
    stream.add_string_data(event, definitions.disasm, instruction.disasm);
}

void add_transaction_metadata(EventStreamProto& stream,
                              EventHandle event,
                              const Definitions& definitions,
                              const InstructionRecord& instruction)
{
    stream.add_uint_data(event, definitions.txid, instruction.seq_num);
}

void emit_marker(EventStreamProto& stream,
                 EventType event_type,
                 std::uint64_t time,
                 const Definitions& definitions,
                 const InstructionRecord& instruction)
{
    auto event = stream.open_event(event_type, time);
    add_transaction_metadata(stream, event, definitions, instruction);
    stream.close_event(event);
}

void emit_stage(EventStreamProto& stream,
                const Definitions& definitions,
                const InstructionRecord& instruction,
                const std::string& stage,
                std::uint64_t time)
{
    auto event = stream.open_event(definitions.stage_events.at(stage), time);
    add_stage_metadata(stream, event, definitions, instruction);
    stream.close_event(event);
}

void convert(std::istream& input,
             EventStreamProto& output,
             const std::string& input_path,
             const std::string& tx_start_stage,
             const std::string& tx_end_stage)
{
    Definitions definitions{
        .start_transaction = output.define_event("start_transaction", "Beginning of a new transaction"),
        .end_transaction = output.define_event("end_transaction", "End of a transaction"),
        .txid = output.define_data("txid", "Transaction ID"),
        .seq_num = output.define_data("seq_num", "gem5 O3PipeView sequence number"),
        .pc = output.define_data("pc", "Instruction program counter"),
        .micro_pc = output.define_data("micro_pc", "Instruction micro-PC"),
        .disasm = output.define_data("disasm", "Instruction disassembly"),
    };

    std::vector<InstructionRecord> instructions;
    std::optional<InstructionRecord> current_instruction;

    std::size_t line_number = 0;
    std::string line;
    while (std::getline(input, line)) {
        ++line_number;

        if (!line.empty() && line.back() == '\r')
            line.pop_back();

        if (!line.starts_with("O3PipeView:"))
            continue;

        if (line.starts_with("O3PipeView:fetch:")) {
            if (current_instruction)
                parse_error(line_number, "encountered fetch before retire for the current instruction");
            current_instruction = parse_fetch_line(line, line_number);
            if (!definitions.stage_events.contains("fetch")) {
                definitions.stage_events.emplace("fetch",
                                                 output.define_event("fetch", "gem5 O3PipeView stage 'fetch'"));
            }
            continue;
        }

        if (!current_instruction)
            parse_error(line_number, "encountered stage before first fetch");

        parse_stage_line(line, line_number, *current_instruction, definitions, output);
        if (current_instruction->stage_times.contains("retire")) {
            instructions.push_back(std::move(*current_instruction));
            current_instruction.reset();
        }
    }

    if (input.bad())
        throw std::runtime_error("failed while reading input trace");
    if (current_instruction)
        throw std::runtime_error("input ended before retire for the current instruction");

    output.set_string_parameter("source_format", "Original trace format", "gem5.o3pipeview");
    output.set_string_parameter("time_unit", "Timestamp unit", "gem5_tick");
    output.set_string_parameter("tx_start_stage", "Stage used to emit start_transaction", tx_start_stage);
    output.set_string_parameter("tx_end_stage", "Stage used to emit end_transaction", tx_end_stage);
    if (input_path != "-")
        output.set_string_parameter("input_path", "Path to the source O3PipeView trace", input_path);
    output.start_simulation();

    for (const auto& instruction : instructions) {
        for (const auto& stage : instruction.stage_order) {
            auto time = instruction.stage_time(stage);
            if (!time || *time == 0)
                continue;

            if (stage == tx_start_stage)
                emit_marker(output, definitions.start_transaction, *time, definitions, instruction);

            emit_stage(output, definitions, instruction, stage, *time);

            if (stage == tx_end_stage)
                emit_marker(output, definitions.end_transaction, *time, definitions, instruction);
        }
    }
}

} // namespace

int main(int argc, char** argv)
{
    try {
        std::string input_path = "-";
        std::string output_path = "-";
        std::string compression_arg = "auto";
        std::string tx_start_stage = "fetch";
        std::string tx_end_stage = "store";
        bool force = false;

        po::options_description desc("Allowed options");
        desc.add_options()("help", "produce help message")(
            "output,o", po::value<std::string>(&output_path)->default_value("-"), "event stream output path")(
            "compress",
            po::value<std::string>(&compression_arg)->default_value("auto"),
            "output compression: auto, none, or xz")(
            "force,f", po::bool_switch(&force), "overwrite an existing output file")(
            "tx-start", po::value<std::string>(&tx_start_stage)->default_value("fetch"), "transaction start stage")(
            "tx-end", po::value<std::string>(&tx_end_stage)->default_value("store"), "transaction end stage")(
            "input", po::value<std::string>(&input_path)->default_value("-"), "O3PipeView trace input path");

        po::positional_options_description positional;
        positional.add("input", 1);

        po::variables_map vm;
        po::store(po::command_line_parser(argc, argv).options(desc).positional(positional).run(), vm);
        po::notify(vm);

        if (vm.count("help")) {
            std::cout << "Usage: " << argv[0] << " [options] [input]\n" << desc << std::endl;
            return 0;
        }

        auto compression = resolve_compression(output_path, compression_arg);
        EventStreamProto output(output_path, force, compression);

        if (input_path == "-") {
            std::cin >> std::noskipws;
            convert(std::cin, output, input_path, tx_start_stage, tx_end_stage);
        } else {
            std::ifstream input(input_path);
            if (!input)
                throw std::runtime_error(fmt::format("failed to open input file '{}'", input_path));
            convert(input, output, input_path, tx_start_stage, tx_end_stage);
        }

        return 0;
    } catch (const std::exception& ex) {
        fmt::print(stderr, "ERROR: {}\n", ex.what());
        return 1;
    }
}
