// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
// Assisted and/or generated by Codex:GPT-5

#include "event_stream/event_stream_proto.h"

#include <boost/program_options.hpp>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <deque>
#include <fmt/base.h>
#include <fmt/format.h>
#include <fstream>
#include <ios>
#include <iostream>
#include <optional>
#include <queue>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <vector>

namespace po = boost::program_options;

namespace {

using perf_streams::event_stream::DataType;
using perf_streams::event_stream::EventHandle;
using perf_streams::event_stream::EventStreamProto;
using perf_streams::event_stream::EventType;

struct StageTime
{
    std::string stage;
    std::uint64_t time{0};

    StageTime(std::string stage_, std::uint64_t time_) : stage(std::move(stage_)), time(time_) {}
};

struct InstructionRecord
{
    std::uint64_t start_time{0};
    std::uint64_t program_counter{0};
    std::uint64_t micro_pc{0};
    std::uint64_t seq_num{0};
    std::string disasm;
    std::vector<StageTime> stage_times;

    void record_stage(std::string stage, std::uint64_t time)
    {
        for (auto& stage_time : stage_times) {
            if (stage_time.stage == stage) {
                stage_time.time = time;
                return;
            }
        }

        stage_times.emplace_back(std::move(stage), time);
    }
};

struct Definitions
{
    EventType start_transaction;
    EventType end_transaction;
    DataType txid;
    DataType seq_num;
    DataType program_counter;
    DataType micro_pc;
    DataType disasm;
    std::unordered_map<std::string, EventType> stage_events;
};

enum class PendingEventKind {
    start_transaction,
    stage,
    end_transaction,
};

struct PendingEvent
{
    std::uint64_t time{0};
    std::size_t instruction_index{0};
    std::size_t stage_index{0};
    PendingEventKind kind{PendingEventKind::stage};

    PendingEvent(std::uint64_t time_, std::size_t instruction_index_, std::size_t stage_index_, PendingEventKind kind_)
        : time(time_), instruction_index(instruction_index_), stage_index(stage_index_), kind(kind_)
    {
    }
};

[[noreturn]] void parse_error(std::size_t line_number, std::string_view message)
{
    throw std::runtime_error(fmt::format("line {}: {}", line_number, message));
}

std::uint64_t parse_u64(std::string_view token, std::size_t line_number, std::string_view field_name)
{
    if (token.empty())
        parse_error(line_number, fmt::format("missing {}", field_name));

    std::size_t consumed = 0;
    std::uint64_t value = 0;
    try {
        value = std::stoull(std::string(token), &consumed, 0);
    } catch (const std::exception&) {
        parse_error(line_number, fmt::format("invalid {} '{}'", field_name, token));
    }

    if (consumed != token.size())
        parse_error(line_number, fmt::format("invalid {} '{}'", field_name, token));

    return value;
}

std::vector<std::string_view> split_all(std::string_view line)
{
    std::vector<std::string_view> parts;
    std::size_t start = 0;
    while (true) {
        auto pos = line.find(':', start);
        if (pos == std::string_view::npos) {
            parts.emplace_back(line.substr(start));
            return parts;
        }

        parts.emplace_back(line.substr(start, pos - start));
        start = pos + 1;
    }
}

InstructionRecord parse_start_line(std::string_view line, std::size_t line_number, const std::string& start_stage)
{
    std::string_view fields[6];
    std::size_t start = 0;
    for (auto& field : fields) {
        std::size_t pos = line.find(':', start);
        if (pos == std::string_view::npos)
            parse_error(line_number, fmt::format("malformed {} line", start_stage));
        field = line.substr(start, pos - start);
        start = pos + 1;
    }

    if (fields[0] != "O3PipeView")
        parse_error(line_number, fmt::format("malformed {} line", start_stage));
    if (fields[1] != start_stage)
        parse_error(line_number, fmt::format("expected {} line", start_stage));

    InstructionRecord record;
    record.start_time = parse_u64(fields[2], line_number, fmt::format("{} time", start_stage));
    record.program_counter = parse_u64(fields[3], line_number, "pc");
    record.micro_pc = parse_u64(fields[4], line_number, "micro_pc");
    record.seq_num = parse_u64(fields[5], line_number, "seq_num");
    record.disasm = std::string(line.substr(start));
    record.record_stage(std::string(start_stage), record.start_time);
    return record;
}

bool parse_stage_line(std::string_view line,
                      std::size_t line_number,
                      InstructionRecord& instruction,
                      Definitions& definitions,
                      EventStreamProto& stream)
{
    auto fields = split_all(line);
    if (fields.size() < 3 || fields[0] != "O3PipeView")
        parse_error(line_number, "malformed stage line");
    if (((fields.size() - 1) % 2) != 0)
        parse_error(line_number, "stage line must contain stage/time pairs");

    bool saw_retire = false;
    for (std::size_t i = 1; i < fields.size(); i += 2) {
        auto stage = fields[i];
        if (stage.empty())
            parse_error(line_number, "empty stage name");

        auto stage_name = std::string(stage);
        instruction.record_stage(stage_name, parse_u64(fields[i + 1], line_number, stage_name + " time"));
        if (stage_name == "retire")
            saw_retire = true;
        if (!definitions.stage_events.contains(stage_name)) {
            definitions.stage_events.emplace(
                stage_name, stream.define_event(stage_name, fmt::format("gem5 O3PipeView stage '{}'", stage_name)));
        }
    }

    return saw_retire;
}

void add_stage_metadata(EventStreamProto& stream,
                        EventHandle event,
                        const Definitions& definitions,
                        const InstructionRecord& instruction)
{
    stream.add_uint_data(event, definitions.txid, instruction.seq_num);
    stream.add_uint_data(event, definitions.seq_num, instruction.seq_num);
    stream.add_uint_data(event, definitions.program_counter, instruction.program_counter);
    stream.add_uint_data(event, definitions.micro_pc, instruction.micro_pc);
    stream.add_string_data(event, definitions.disasm, instruction.disasm);
}

void add_transaction_metadata(EventStreamProto& stream,
                              EventHandle event,
                              const Definitions& definitions,
                              const InstructionRecord& instruction)
{
    stream.add_uint_data(event, definitions.txid, instruction.seq_num);
}

void emit_marker(EventStreamProto& stream,
                 EventType event_type,
                 std::uint64_t time,
                 const Definitions& definitions,
                 const InstructionRecord& instruction)
{
    auto event = stream.open_event(event_type, time);
    add_transaction_metadata(stream, event, definitions, instruction);
    stream.close_event(event);
}

void emit_stage(EventStreamProto& stream,
                const Definitions& definitions,
                const InstructionRecord& instruction,
                const std::string& stage,
                std::uint64_t time)
{
    auto event = stream.open_event(definitions.stage_events.at(stage), time);
    add_stage_metadata(stream, event, definitions, instruction);
    stream.close_event(event);
}

int pending_event_kind_order(PendingEventKind kind)
{
    switch (kind) {
    case PendingEventKind::start_transaction:
        return 0;
    case PendingEventKind::stage:
        return 1;
    case PendingEventKind::end_transaction:
        return 2;
    }

    throw std::logic_error("unknown pending event kind");
}

bool pending_event_less(const PendingEvent& left, const PendingEvent& right)
{
    return std::tuple(left.time, left.instruction_index, left.stage_index, pending_event_kind_order(left.kind))
           < std::tuple(right.time, right.instruction_index, right.stage_index, pending_event_kind_order(right.kind));
}

struct PendingEventCompare
{
    bool operator()(const PendingEvent& left, const PendingEvent& right) const
    {
        return pending_event_less(right, left);
    }
};

std::optional<PendingEvent> first_pending_event_for_stage(const InstructionRecord& instruction,
                                                          std::size_t instruction_index,
                                                          std::size_t stage_index,
                                                          const std::string& tx_start_stage)
{
    for (; stage_index < instruction.stage_times.size(); ++stage_index) {
        const auto& stage_time = instruction.stage_times[stage_index];
        if (stage_time.time == 0)
            continue;

        auto kind = stage_time.stage == tx_start_stage ? PendingEventKind::start_transaction : PendingEventKind::stage;
        return PendingEvent(stage_time.time, instruction_index, stage_index, kind);
    }

    return std::nullopt;
}

std::optional<PendingEvent> next_pending_event(const InstructionRecord& instruction,
                                               const PendingEvent& current_event,
                                               const std::string& tx_start_stage,
                                               const std::string& tx_end_stage)
{
    const auto& stage_time = instruction.stage_times[current_event.stage_index];
    switch (current_event.kind) {
    case PendingEventKind::start_transaction:
        return PendingEvent(
            stage_time.time, current_event.instruction_index, current_event.stage_index, PendingEventKind::stage);
    case PendingEventKind::stage:
        if (stage_time.stage == tx_end_stage) {
            return PendingEvent(stage_time.time,
                                current_event.instruction_index,
                                current_event.stage_index,
                                PendingEventKind::end_transaction);
        }
        break;
    case PendingEventKind::end_transaction:
        break;
    }

    return first_pending_event_for_stage(
        instruction, current_event.instruction_index, current_event.stage_index + 1, tx_start_stage);
}

void retire_completed_instructions(std::deque<InstructionRecord>& instructions,
                                   std::vector<bool>& instruction_completed,
                                   std::size_t& first_instruction_index)
{
    while (!instructions.empty() && instruction_completed[first_instruction_index]) {
        instructions.pop_front();
        ++first_instruction_index;
    }
}

void emit_pending_events(std::deque<InstructionRecord>& instructions,
                         EventStreamProto& output,
                         const Definitions& definitions,
                         const std::string& tx_start_stage,
                         const std::string& tx_end_stage)
{
    std::priority_queue<PendingEvent, std::vector<PendingEvent>, PendingEventCompare> pending_events;
    std::vector<bool> instruction_completed(instructions.size(), false);
    for (std::size_t instruction_index = 0; instruction_index < instructions.size(); ++instruction_index) {
        const auto& instruction = instructions[instruction_index];
        if (auto pending_event = first_pending_event_for_stage(instruction, instruction_index, 0, tx_start_stage)) {
            pending_events.emplace(*pending_event);
        } else {
            instruction_completed[instruction_index] = true;
        }
    }

    std::size_t first_instruction_index = 0;
    retire_completed_instructions(instructions, instruction_completed, first_instruction_index);

    while (!pending_events.empty()) {
        auto pending_event = pending_events.top();
        pending_events.pop();

        const auto& instruction = instructions.at(pending_event.instruction_index - first_instruction_index);
        const auto& stage_time = instruction.stage_times[pending_event.stage_index];
        switch (pending_event.kind) {
        case PendingEventKind::start_transaction:
            emit_marker(output, definitions.start_transaction, pending_event.time, definitions, instruction);
            break;
        case PendingEventKind::stage:
            emit_stage(output, definitions, instruction, stage_time.stage, pending_event.time);
            break;
        case PendingEventKind::end_transaction:
            emit_marker(output, definitions.end_transaction, pending_event.time, definitions, instruction);
            break;
        }

        if (auto next_event = next_pending_event(instruction, pending_event, tx_start_stage, tx_end_stage)) {
            pending_events.emplace(*next_event);
        } else {
            instruction_completed[pending_event.instruction_index] = true;
            retire_completed_instructions(instructions, instruction_completed, first_instruction_index);
        }
    }
}

void convert(std::istream& input,
             EventStreamProto& output,
             const std::string& input_path,
             const std::string& tx_start_stage,
             const std::string& tx_end_stage)
{
    Definitions definitions{
        .start_transaction = output.define_event("start_transaction", "Beginning of a new transaction"),
        .end_transaction = output.define_event("end_transaction", "End of a transaction"),
        .txid = output.define_data("txid", "Transaction ID"),
        .seq_num = output.define_data("seq_num", "gem5 O3PipeView sequence number"),
        .program_counter = output.define_data("program_counter", "Instruction program counter"),
        .micro_pc = output.define_data("micro_pc", "Instruction micro-PC"),
        .disasm = output.define_data("disasm", "Instruction disassembly"),
    };

    std::deque<InstructionRecord> instructions;
    std::optional<InstructionRecord> current_instruction;

    std::size_t line_number = 0;
    std::string line;
    while (std::getline(input, line)) {
        ++line_number;

        if (!line.empty() && line.back() == '\r')
            line.pop_back();

        if (!line.starts_with("O3PipeView:"))
            continue;

        if (line.starts_with(fmt::format("O3PipeView:{}:", tx_start_stage))) {
            if (current_instruction)
                parse_error(line_number,
                            fmt::format("encountered {} before retire for the current instruction", tx_start_stage));
            current_instruction = parse_start_line(line, line_number, tx_start_stage);
            if (!definitions.stage_events.contains(tx_start_stage)) {
                definitions.stage_events.emplace(
                    tx_start_stage,
                    output.define_event(tx_start_stage, fmt::format("gem5 O3PipeView stage '{}'", tx_start_stage)));
            }
            continue;
        }

        if (!current_instruction)
            parse_error(line_number, fmt::format("encountered stage before first {}", tx_start_stage));

        if (parse_stage_line(line, line_number, *current_instruction, definitions, output)) {
            instructions.emplace_back(std::move(*current_instruction));
            current_instruction.reset();
        }
    }

    if (input.bad())
        throw std::runtime_error("failed while reading input trace");
    if (current_instruction)
        throw std::runtime_error("input ended before retire for the current instruction");

    output.set_string_parameter("source_format", "Original trace format", "gem5.o3pipeview");
    output.set_string_parameter("time_unit", "Timestamp unit", "gem5_tick");
    output.set_string_parameter("tx_start_stage", "Stage used to emit start_transaction", tx_start_stage);
    output.set_string_parameter("tx_end_stage", "Stage used to emit end_transaction", tx_end_stage);
    if (input_path != "-")
        output.set_string_parameter("input_path", "Path to the source O3PipeView trace", input_path);
    output.start_simulation();

    emit_pending_events(instructions, output, definitions, tx_start_stage, tx_end_stage);
}

} // namespace

int main(int argc, char** argv)
{
    try {
        std::string input_path = "-";
        std::string output_path = "-";
        std::string tx_start_stage = "fetch";
        std::string tx_end_stage = "store";
        bool force = false;

        po::options_description desc("Allowed options");
        desc.add_options()("help,h", "produce help message")(
            "output,o", po::value<std::string>(&output_path)->default_value("-"), "event stream output path")(
            "force,f", po::bool_switch(&force), "overwrite an existing output file")(
            "tx-start",
            po::value<std::string>(&tx_start_stage)->default_value("fetch"),
            "transaction start stage and O3PipeView opener")(
            "tx-end", po::value<std::string>(&tx_end_stage)->default_value("store"), "transaction end stage")(
            "input", po::value<std::string>(&input_path)->default_value("-"), "O3PipeView trace input path");

        po::positional_options_description positional;
        positional.add("input", 1);

        po::variables_map vm;
        po::store(po::command_line_parser(argc, argv).options(desc).positional(positional).run(), vm);
        po::notify(vm);

        if (vm.count("help")) {
            std::cout << "Usage: " << argv[0] << " [options] [input]\n\n";
            std::cout << "Convert gem5 o3pipeview debug trace to event-stream\n\n";
            std::cout << desc << std::endl;
            return EXIT_SUCCESS;
        }

        std::optional<std::ifstream> input_file;
        if (input_path != "-") {
            input_file.emplace(input_path);
            if (!*input_file)
                throw std::runtime_error(fmt::format("failed to open input file '{}'", input_path));
        }

        EventStreamProto output(output_path, force);
        if (input_path == "-") {
            std::cin >> std::noskipws;
            convert(std::cin, output, input_path, tx_start_stage, tx_end_stage);
        } else {
            convert(*input_file, output, input_path, tx_start_stage, tx_end_stage);
        }

        return EXIT_SUCCESS;
    } catch (const std::exception& ex) {
        fmt::print(stderr, "ERROR: {}\n", ex.what());
        return EXIT_FAILURE;
    }
}
