# Copyright (c) 2026, Ampere Computing LLC
# SPDX-License-Identifier: BSD-3-Clause
#
# Assisted and/or generated by Codex:GPT-5

"""STDIO MCP server and direct tool functions for event streams."""

from __future__ import annotations

import argparse
import sys
from typing import Any

from perf_streams import _event_stream_mcp

mcp_import_error: ImportError | None = None
try:
    from mcp.server.fastmcp import FastMCP
except ImportError as exc:
    mcp_import_error = exc
    FastMCP = None


def event_stream_inspect(path: str, include_values: bool = True, include_params: bool = True) -> dict[str, Any]:
    """Inspect an event stream."""
    return _event_stream_mcp.inspect(path, include_values=include_values, include_params=include_params)


def event_stream_count(  # noqa: PLR0913
    path: str,
    events: list[str] | str | None = None,
    exclude: list[str] | str | None = None,
    accumulate: list[str] | str | None = None,
    start: int | str | None = None,
    stop: int | str | None = None,
    interval: int | str | None = None,
    expand_enums: bool = True,
) -> dict[str, Any]:
    """Count events and event values.

    You can also "factor" events on data items and count those factors individually. What this means is that if you have an event, for example, cache.lookup and it is posted with a data item called hit which has a value of 0 or 1, then you can separate the counts where hit is 0 and hit is 1 by specifying cache.lookup/hit. The resulting metrics will have the names cache.lookup/hit:0 and cache.lookup/hit:1 (though see the rename plugin for how to change these names).

    It is common to have event and data items declared as siblings in the same module scope. For example, cache.lookup might be the full event name, and cache.hit might be the data name. If you want to use hit as a factor, you can still refer to this as cache.lookup/hit. The processor will first try to find hit in the same scope as lookup (that is, it will prepend the cache. automatically). If that fails, it will try to find hit as a global data name. If you need to force hit to be a global name, due to a name conflict, you can prepend a '.' like this: cache.lookup/.hit.

    An event may have any number of factors: event/data1/data2/.... The counts will be split up into all combinations. It is possible to see in the output a metric name which does not include all data items. This happens if the event is posted without that data item on at least one occasion. The base event (total) count is also always included.

    Data factors must have integer types to be used as factors today. There is no factoring on strings or floating point data.

    Values can be restricted either by:

        */factor_name:value: counts only events where factor_name = value
        */factor_name[min:max:granularity:sequence]: adjusts factor value into a "histogram" format where:
        min: minimum value emitted, any values below this will be set to min
        max: maximum value emitted, any values above this will be set to max
        granularity: granularity of value emitted (depends on sequence)
        sequence: how the granularity is used, either:
        linear (default): linear sequence of granularity. For example values 1,2,3,4 with a granularity of 2 would become 0,2,2,4
        exp|exponential: exponential sequence, where granularity is the base. For example values 1,3,5,10 with a granularity of 2 would become 1,2,4,8 for example values 1,2,3,4 with a granularity of 2 would become 0,2,2,4
    """
    return _event_stream_mcp.count(
        path,
        events=events,
        exclude=exclude,
        accumulate=accumulate,
        start=start,
        stop=stop,
        interval=interval,
        expand_enums=expand_enums,
    )


def event_stream_latency(  # noqa: PLR0913
    path: str,
    events: list[str],
    name: str | None = None,
    key: str | None = None,
    prefix: str | None = None,
    histogram: str | None = None,
    factored: bool = False,
    ignore_missing: bool = False,
) -> dict[str, Any]:
    """Measure latency between named events."""
    return _event_stream_mcp.latency(
        path,
        events,
        name=name,
        key=key,
        prefix=prefix,
        histogram=histogram,
        factored=factored,
        ignore_missing=ignore_missing,
    )


def event_stream_rate(
    path: str,
    interval: str,
    events: list[str] | str,
    suffix: str = "rate",
    factored: bool = False,
) -> dict[str, Any]:
    """Build a histogram of event counts per interval."""
    return _event_stream_mcp.rate(path, interval, events, suffix=suffix, factored=factored)


def event_stream_params(path: str, params: list[str] | str | None = None, all: bool = False) -> dict[str, Any]:  # noqa: A002
    """Return event stream parameters."""
    return _event_stream_mcp.params(path, params=params, all=all)


def event_stream_sample(  # noqa: PLR0913
    path: str,
    events: list[str] | str | None = None,
    start: int | str | None = None,
    stop: int | str | None = None,
    limit: int = 100,
    expand_enums: bool = True,
) -> dict[str, Any]:
    """Return a bounded structured sample of events."""
    return _event_stream_mcp.sample(
        path,
        events=events,
        start=start,
        stop=stop,
        limit=limit,
        expand_enums=expand_enums,
    )


def event_stream_cache(action: str = "stats", path: str | None = None, memory_budget: int = 0) -> dict[str, Any]:
    """Return cache stats or clear/configure the cache."""
    return _event_stream_mcp.cache(action, path=path, memory_budget=memory_budget)


def _run_mcp_server() -> int:
    if FastMCP is None:
        sys.stderr.write(f"Python MCP SDK is required to run the server: {mcp_import_error}\n")
        return 1

    server = FastMCP("perf-streams-event-stream")
    server.tool()(event_stream_inspect)
    server.tool()(event_stream_count)
    server.tool()(event_stream_latency)
    server.tool()(event_stream_rate)
    server.tool()(event_stream_params)
    server.tool()(event_stream_sample)
    server.tool()(event_stream_cache)
    server.run(transport="stdio")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the STDIO-only MCP server."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--stdio",
        action="store_true",
        default=True,
        help=argparse.SUPPRESS,
    )
    parser.parse_args(argv)
    return _run_mcp_server()


if __name__ == "__main__":
    raise SystemExit(main())
