# Copyright (c) 2026, Ampere Computing LLC
# SPDX-License-Identifier: BSD-3-Clause
#
# Assisted and/or generated by Codex:GPT-5

"""STDIO MCP server and direct tool functions for event streams."""

from __future__ import annotations

import argparse
import sys
from typing import Any

from perf_streams import _event_stream_mcp

mcp_import_error: ImportError | None = None
try:
    from mcp.server.fastmcp import FastMCP
except ImportError as exc:
    mcp_import_error = exc
    FastMCP = None


def event_stream_inspect(path: str, include_values: bool = True, include_params: bool = True) -> dict[str, Any]:
    """Inspect an event stream."""
    return _event_stream_mcp.inspect(path, include_values=include_values, include_params=include_params)


def event_stream_count(  # noqa: PLR0913
    path: str,
    events: list[str] | str | None = None,
    exclude: list[str] | str | None = None,
    accumulate: list[str] | str | None = None,
    start: int | str | None = None,
    stop: int | str | None = None,
    interval: int | str | None = None,
    expand_enums: bool = True,
) -> dict[str, Any]:
    """Count events and event values."""
    return _event_stream_mcp.count(
        path,
        events=events,
        exclude=exclude,
        accumulate=accumulate,
        start=start,
        stop=stop,
        interval=interval,
        expand_enums=expand_enums,
    )


def event_stream_latency(  # noqa: PLR0913
    path: str,
    events: list[str],
    name: str | None = None,
    key: str | None = None,
    prefix: str | None = None,
    histogram: str | None = None,
    factored: bool = False,
    ignore_missing: bool = False,
) -> dict[str, Any]:
    """Measure latency between named events."""
    return _event_stream_mcp.latency(
        path,
        events,
        name=name,
        key=key,
        prefix=prefix,
        histogram=histogram,
        factored=factored,
        ignore_missing=ignore_missing,
    )


def event_stream_rate(
    path: str,
    interval: str,
    events: list[str] | str,
    suffix: str = "rate",
    factored: bool = False,
) -> dict[str, Any]:
    """Build a histogram of event counts per interval."""
    return _event_stream_mcp.rate(path, interval, events, suffix=suffix, factored=factored)


def event_stream_params(path: str, params: list[str] | str | None = None, all: bool = False) -> dict[str, Any]:  # noqa: A002
    """Return event stream parameters."""
    return _event_stream_mcp.params(path, params=params, all=all)


def event_stream_sample(  # noqa: PLR0913
    path: str,
    events: list[str] | str | None = None,
    start: int | str | None = None,
    stop: int | str | None = None,
    limit: int = 100,
    expand_enums: bool = True,
) -> dict[str, Any]:
    """Return a bounded structured sample of events."""
    return _event_stream_mcp.sample(
        path,
        events=events,
        start=start,
        stop=stop,
        limit=limit,
        expand_enums=expand_enums,
    )


def event_stream_cache(action: str = "stats", path: str | None = None, memory_budget: int = 0) -> dict[str, Any]:
    """Return cache stats or clear/configure the cache."""
    return _event_stream_mcp.cache(action, path=path, memory_budget=memory_budget)


def _run_mcp_server() -> int:
    if FastMCP is None:
        sys.stderr.write(f"Python MCP SDK is required to run the server: {mcp_import_error}\n")
        return 1

    server = FastMCP("perf-streams-event-stream")
    server.tool()(event_stream_inspect)
    server.tool()(event_stream_count)
    server.tool()(event_stream_latency)
    server.tool()(event_stream_rate)
    server.tool()(event_stream_params)
    server.tool()(event_stream_sample)
    server.tool()(event_stream_cache)
    server.run(transport="stdio")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the STDIO-only MCP server."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--stdio",
        action="store_true",
        default=True,
        help=argparse.SUPPRESS,
    )
    parser.parse_args(argv)
    return _run_mcp_server()


if __name__ == "__main__":
    raise SystemExit(main())
