// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:GPT-5

#include "event_stream/mcp/query.h"
#include "event_stream/processor/utils.h"

#include <cstdint>
#include <optional>
#include <pybind11/pybind11.h>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

namespace py = pybind11;
namespace mcp = perf_streams::event_stream::mcp;
namespace processor = perf_streams::event_stream::processor;

namespace {

py::object py_scalar_value(const mcp::Scalar& scalar)
{
    switch (scalar.kind) {
    case mcp::Scalar::Kind::NONE:
        return py::none();
    case mcp::Scalar::Kind::BOOL:
        return py::bool_(std::get<bool>(scalar.value));
    case mcp::Scalar::Kind::INT:
        return py::int_(std::get<int64_t>(scalar.value));
    case mcp::Scalar::Kind::UINT:
        return py::int_(std::get<uint64_t>(scalar.value));
    case mcp::Scalar::Kind::DOUBLE:
        return py::float_(std::get<double>(scalar.value));
    case mcp::Scalar::Kind::STRING:
    case mcp::Scalar::Kind::JSON:
        return py::str(std::get<std::string>(scalar.value));
    }
    return py::none();
}

py::dict py_metric(const mcp::Metric& metric)
{
    py::dict dict;
    dict["name"] = metric.name;
    dict["value"] = py_scalar_value(metric.value);
    dict["value_type"] = metric.value.type_name();
    return dict;
}

template<typename T, typename Convert>
py::list py_list(const std::vector<T>& values, Convert convert)
{
    py::list list;
    for (const auto& value : values)
        list.append(convert(value));
    return list;
}

py::dict py_definition(const mcp::DefinitionInfo& definition)
{
    py::dict dict;
    dict["kind"] = definition.kind;
    dict["id"] = definition.id;
    dict["name"] = definition.name;
    dict["description"] = definition.description;
    if (definition.enumeration_id)
        dict["enumeration_id"] = *definition.enumeration_id;
    else
        dict["enumeration_id"] = py::none();
    return dict;
}

py::dict py_enumeration(const mcp::EnumerationInfo& enumeration)
{
    py::dict values;
    for (const auto& [value, name] : enumeration.values)
        values[py::int_(value)] = name;

    py::dict dict;
    dict["id"] = enumeration.id;
    dict["values"] = values;
    return dict;
}

py::dict py_parameter(const mcp::ParameterInfo& parameter)
{
    py::dict dict;
    dict["name"] = parameter.name;
    dict["description"] = parameter.description;
    dict["value"] = py_scalar_value(parameter.value);
    dict["value_type"] = parameter.value.type_name();
    return dict;
}

py::dict py_event_value(const mcp::EventValue& value)
{
    py::dict dict;
    dict["definition_id"] = value.definition_id;
    dict["name"] = value.name;
    dict["value"] = py_scalar_value(value.value);
    dict["value_type"] = value.value.type_name();
    if (value.expanded)
        dict["expanded"] = *value.expanded;
    else
        dict["expanded"] = py::none();
    return dict;
}

py::dict py_event(const mcp::EventSample& event)
{
    py::dict dict;
    dict["id"] = event.id;
    dict["definition_id"] = event.definition_id;
    dict["name"] = event.name;
    dict["time"] = event.time;
    dict["values"] = py_list(event.values, py_event_value);
    return dict;
}

py::dict py_series_bucket(const mcp::SeriesBucket& bucket)
{
    py::dict dict;
    dict["start"] = bucket.start;
    dict["stop"] = bucket.stop;
    dict["metrics"] = py_list(bucket.metrics, py_metric);
    return dict;
}

std::vector<std::string> py_strings(const py::object& obj)
{
    std::vector<std::string> values;
    if (obj.is_none())
        return values;

    if (py::isinstance<py::str>(obj)) {
        values.emplace_back(py::cast<std::string>(obj));
        return values;
    }

    if (!PySequence_Check(obj.ptr()))
        throw std::runtime_error{"expected a string or sequence of strings"};

    for (const auto& item : obj) {
        if (!py::isinstance<py::str>(item))
            throw std::runtime_error{"expected a string or sequence of strings"};
        values.emplace_back(py::cast<std::string>(item));
    }
    return values;
}

std::optional<uint64_t> py_time(const py::object& obj)
{
    if (obj.is_none())
        return {};
    if (py::isinstance<py::int_>(obj))
        return py::cast<uint64_t>(obj);
    if (py::isinstance<py::str>(obj))
        return processor::parse_time_spec(py::cast<std::string>(obj));
    throw std::runtime_error{"expected an integer time or time specification string"};
}

py::dict py_inspect(const std::string& path, bool include_values, bool include_params)
{
    auto result = mcp::inspect(path, {.include_values = include_values, .include_params = include_params});

    py::dict time_range;
    if (result.first_time)
        time_range["first"] = *result.first_time;
    else
        time_range["first"] = py::none();
    if (result.last_time)
        time_range["last"] = *result.last_time;
    else
        time_range["last"] = py::none();

    py::dict counts;
    for (const auto& [name, value] : result.counts_by_definition)
        counts[py::str(name)] = value;

    py::dict dict;
    dict["path"] = result.path.string();
    dict["stream_version"] = result.stream_version;
    dict["definitions"] = py_list(result.definitions, py_definition);
    dict["enumerations"] = py_list(result.enumerations, py_enumeration);
    dict["parameters"] = py_list(result.parameters, py_parameter);
    dict["time_range"] = time_range;
    dict["event_count"] = result.event_count;
    dict["counts_by_definition"] = counts;
    return dict;
}

py::dict py_count(const std::string& path,
                  const py::object& events,
                  const py::object& exclude,
                  const py::object& accumulate,
                  const py::object& start,
                  const py::object& stop,
                  const py::object& interval,
                  bool expand_enums)
{
    mcp::CountOptions options;
    options.events = py_strings(events);
    options.exclude = py_strings(exclude);
    options.accumulate = py_strings(accumulate);
    options.start = py_time(start);
    options.stop = py_time(stop);
    options.interval = py_time(interval);
    options.expand_enums = expand_enums;

    auto result = mcp::count(path, options);

    py::dict dict;
    dict["summary"] = py_list(result.summary, py_metric);
    dict["series"] = py_list(result.series, py_series_bucket);
    return dict;
}

py::dict py_latency(const std::string& path,
                    const py::object& events,
                    const py::object& name,
                    const py::object& key,
                    const py::object& prefix,
                    const py::object& histogram,
                    bool factored,
                    bool ignore_missing)
{
    mcp::LatencyOptions options;
    options.events = py_strings(events);
    if (!name.is_none())
        options.name = py::cast<std::string>(name);
    if (!key.is_none())
        options.key = py::cast<std::string>(key);
    if (!prefix.is_none())
        options.prefix = py::cast<std::string>(prefix);
    if (!histogram.is_none())
        options.histogram = py::cast<std::string>(histogram);
    options.factored = factored;
    options.ignore_missing = ignore_missing;

    auto result = mcp::latency(path, options);

    py::dict dict;
    dict["summary"] = py_list(result.summary, py_metric);
    return dict;
}

py::dict py_rate(const std::string& path,
                 const std::string& interval,
                 const py::object& events,
                 const std::string& suffix,
                 bool factored)
{
    mcp::RateOptions options;
    options.interval = interval;
    options.events = py_strings(events);
    options.suffix = suffix;
    options.factored = factored;

    auto result = mcp::rate(path, options);

    py::dict dict;
    dict["summary"] = py_list(result.summary, py_metric);
    return dict;
}

py::dict py_params(const std::string& path, const py::object& params, bool all)
{
    mcp::ParamsOptions options;
    options.params = py_strings(params);
    options.all = all;

    auto result = mcp::params(path, options);

    py::dict dict;
    dict["parameters"] = py_list(result.parameters, py_parameter);
    return dict;
}

py::dict py_sample(const std::string& path,
                   const py::object& events,
                   const py::object& start,
                   const py::object& stop,
                   uint64_t limit,
                   bool expand_enums)
{
    mcp::SampleOptions options;
    options.events = py_strings(events);
    options.start = py_time(start);
    options.stop = py_time(stop);
    options.limit = limit;
    options.expand_enums = expand_enums;

    auto result = mcp::sample(path, options);

    py::dict dict;
    dict["events"] = py_list(result.events, py_event);
    dict["truncated"] = result.truncated;
    return dict;
}

py::dict py_cache(const std::string& action, const py::object& path, uint64_t memory_budget)
{
    if (action == "clear") {
        if (path.is_none())
            mcp::clear_cache();
        else
            mcp::clear_cache(py::cast<std::string>(path));
    } else if (action == "set_memory_budget") {
        mcp::set_memory_budget(memory_budget);
    } else if (action != "stats") {
        throw std::runtime_error{"cache action must be stats, clear, or set_memory_budget"};
    }

    auto stats = mcp::cache_stats();

    py::dict dict;
    dict["streams"] = stats.streams;
    dict["aggregate_results"] = stats.aggregate_results;
    dict["memory_budget_bytes"] = stats.memory_budget_bytes;
    dict["estimated_memory_bytes"] = stats.estimated_memory_bytes;
    return dict;
}

} // namespace

PYBIND11_MODULE(_event_stream_mcp, module)
{
    module.doc() = "C++ event stream analysis helpers for the MCP server.";

    module.def("inspect",
               &py_inspect,
               py::arg("path"),
               py::arg("include_values") = true,
               py::arg("include_params") = true,
               "Inspect an event stream.");
    module.def("count",
               &py_count,
               py::arg("path"),
               py::arg("events") = py::none(),
               py::arg("exclude") = py::none(),
               py::arg("accumulate") = py::none(),
               py::arg("start") = py::none(),
               py::arg("stop") = py::none(),
               py::arg("interval") = py::none(),
               py::arg("expand_enums") = true,
               "Count event stream records.");
    module.def("latency",
               &py_latency,
               py::arg("path"),
               py::arg("events"),
               py::arg("name") = py::none(),
               py::arg("key") = py::none(),
               py::arg("prefix") = py::none(),
               py::arg("histogram") = py::none(),
               py::arg("factored") = false,
               py::arg("ignore_missing") = false,
               "Measure event stream latency.");
    module.def("rate",
               &py_rate,
               py::arg("path"),
               py::arg("interval"),
               py::arg("events"),
               py::arg("suffix") = "rate",
               py::arg("factored") = false,
               "Measure event stream rates.");
    module.def("params",
               &py_params,
               py::arg("path"),
               py::arg("params") = py::none(),
               py::arg("all") = false,
               "Read event stream parameters.");
    module.def("sample",
               &py_sample,
               py::arg("path"),
               py::arg("events") = py::none(),
               py::arg("start") = py::none(),
               py::arg("stop") = py::none(),
               py::arg("limit") = 100,
               py::arg("expand_enums") = true,
               "Sample event stream events.");
    module.def("cache",
               &py_cache,
               py::arg("action"),
               py::arg("path") = py::none(),
               py::arg("memory_budget") = 0,
               "Manage the event stream cache.");
}
