// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:GPT-5

#define PY_SSIZE_T_CLEAN
#include "event_stream/mcp/query.h"
#include "event_stream/processor/utils.h"

#include <Python.h>
#include <cstdint>
#include <exception>
#include <filesystem>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace mcp = perf_streams::event_stream::mcp;
namespace processor = perf_streams::event_stream::processor;

namespace {

int set_new(PyObject* dict, const char* key, PyObject* value)
{
    if (!value)
        return -1;
    int result = PyDict_SetItemString(dict, key, value);
    Py_DECREF(value);
    return result;
}

PyObject* py_scalar_value(const mcp::Scalar& scalar)
{
    switch (scalar.kind) {
    case mcp::Scalar::Kind::NONE:
        Py_RETURN_NONE;
    case mcp::Scalar::Kind::BOOL:
        return PyBool_FromLong(std::get<bool>(scalar.value));
    case mcp::Scalar::Kind::INT:
        return PyLong_FromLongLong(std::get<int64_t>(scalar.value));
    case mcp::Scalar::Kind::UINT:
        return PyLong_FromUnsignedLongLong(std::get<uint64_t>(scalar.value));
    case mcp::Scalar::Kind::DOUBLE:
        return PyFloat_FromDouble(std::get<double>(scalar.value));
    case mcp::Scalar::Kind::STRING:
    case mcp::Scalar::Kind::JSON:
        return PyUnicode_FromString(std::get<std::string>(scalar.value).c_str());
    }
    Py_RETURN_NONE;
}

PyObject* py_metric(const mcp::Metric& metric)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "name", PyUnicode_FromString(metric.name.c_str())) < 0
        || set_new(dict, "value", py_scalar_value(metric.value)) < 0
        || set_new(dict, "value_type", PyUnicode_FromString(metric.value.type_name().c_str())) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    return dict;
}

template<typename T, typename Convert>
PyObject* py_list(const std::vector<T>& values, Convert convert)
{
    auto* list = PyList_New(static_cast<Py_ssize_t>(values.size()));
    if (!list)
        return nullptr;
    for (Py_ssize_t idx = 0; idx < static_cast<Py_ssize_t>(values.size()); ++idx) {
        auto* item = convert(values[static_cast<size_t>(idx)]);
        if (!item) {
            Py_DECREF(list);
            return nullptr;
        }
        PyList_SET_ITEM(list, idx, item);
    }
    return list;
}

PyObject* py_definition(const mcp::DefinitionInfo& definition)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "kind", PyUnicode_FromString(definition.kind.c_str())) < 0
        || set_new(dict, "id", PyLong_FromUnsignedLong(definition.id)) < 0
        || set_new(dict, "name", PyUnicode_FromString(definition.name.c_str())) < 0
        || set_new(dict, "description", PyUnicode_FromString(definition.description.c_str())) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    if (definition.enumeration_id) {
        if (set_new(dict, "enumeration_id", PyLong_FromUnsignedLong(*definition.enumeration_id)) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
    } else {
        Py_INCREF(Py_None);
        if (PyDict_SetItemString(dict, "enumeration_id", Py_None) < 0) {
            Py_DECREF(Py_None);
            Py_DECREF(dict);
            return nullptr;
        }
        Py_DECREF(Py_None);
    }
    return dict;
}

PyObject* py_enumeration(const mcp::EnumerationInfo& enumeration)
{
    auto* dict = PyDict_New();
    auto* values = PyDict_New();
    if (!dict || !values) {
        Py_XDECREF(dict);
        Py_XDECREF(values);
        return nullptr;
    }
    for (const auto& [value, name] : enumeration.values) {
        auto* key = PyLong_FromLongLong(value);
        auto* py_name = PyUnicode_FromString(name.c_str());
        if (!key || !py_name || PyDict_SetItem(values, key, py_name) < 0) {
            Py_XDECREF(key);
            Py_XDECREF(py_name);
            Py_DECREF(values);
            Py_DECREF(dict);
            return nullptr;
        }
        Py_DECREF(key);
        Py_DECREF(py_name);
    }
    if (set_new(dict, "id", PyLong_FromUnsignedLong(enumeration.id)) < 0 || set_new(dict, "values", values) < 0) {
        Py_DECREF(dict);
        return nullptr;
    }
    return dict;
}

PyObject* py_parameter(const mcp::ParameterInfo& parameter)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "name", PyUnicode_FromString(parameter.name.c_str())) < 0
        || set_new(dict, "description", PyUnicode_FromString(parameter.description.c_str())) < 0
        || set_new(dict, "value", py_scalar_value(parameter.value)) < 0
        || set_new(dict, "value_type", PyUnicode_FromString(parameter.value.type_name().c_str())) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    return dict;
}

PyObject* py_event_value(const mcp::EventValue& value)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "definition_id", PyLong_FromUnsignedLong(value.definition_id)) < 0
        || set_new(dict, "name", PyUnicode_FromString(value.name.c_str())) < 0
        || set_new(dict, "value", py_scalar_value(value.value)) < 0
        || set_new(dict, "value_type", PyUnicode_FromString(value.value.type_name().c_str())) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    if (value.expanded) {
        if (set_new(dict, "expanded", PyUnicode_FromString(value.expanded->c_str())) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
    } else {
        if (set_new(dict, "expanded", Py_NewRef(Py_None)) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
    }
    return dict;
}

PyObject* py_event(const mcp::EventSample& event)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "id", PyLong_FromUnsignedLongLong(event.id)) < 0
        || set_new(dict, "definition_id", PyLong_FromUnsignedLong(event.definition_id)) < 0
        || set_new(dict, "name", PyUnicode_FromString(event.name.c_str())) < 0
        || set_new(dict, "time", PyLong_FromUnsignedLongLong(event.time)) < 0
        || set_new(dict, "values", py_list(event.values, py_event_value)) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    return dict;
}

PyObject* py_series_bucket(const mcp::SeriesBucket& bucket)
{
    auto* dict = PyDict_New();
    if (!dict)
        return nullptr;
    if (set_new(dict, "start", PyLong_FromUnsignedLongLong(bucket.start)) < 0
        || set_new(dict, "stop", PyLong_FromUnsignedLongLong(bucket.stop)) < 0
        || set_new(dict, "metrics", py_list(bucket.metrics, py_metric)) < 0)
    {
        Py_DECREF(dict);
        return nullptr;
    }
    return dict;
}

std::vector<std::string> py_strings(PyObject* obj)
{
    std::vector<std::string> values;
    if (!obj || obj == Py_None)
        return values;
    if (PyUnicode_Check(obj)) {
        values.emplace_back(PyUnicode_AsUTF8(obj));
        return values;
    }
    auto* seq = PySequence_Fast(obj, "expected a string or sequence of strings");
    if (!seq)
        throw std::runtime_error{"expected a string or sequence of strings"};
    auto* items = PySequence_Fast_ITEMS(seq);
    auto size = PySequence_Fast_GET_SIZE(seq);
    for (Py_ssize_t idx = 0; idx < size; ++idx) {
        if (!PyUnicode_Check(items[idx])) {
            Py_DECREF(seq);
            throw std::runtime_error{"expected a string or sequence of strings"};
        }
        values.emplace_back(PyUnicode_AsUTF8(items[idx]));
    }
    Py_DECREF(seq);
    return values;
}

std::optional<uint64_t> py_time(PyObject* obj)
{
    if (!obj || obj == Py_None)
        return {};
    if (PyLong_Check(obj))
        return PyLong_AsUnsignedLongLong(obj);
    if (PyUnicode_Check(obj))
        return processor::parse_time_spec(PyUnicode_AsUTF8(obj));
    throw std::runtime_error{"expected an integer time or time specification string"};
}

PyObject* translate_exception()
{
    try {
        throw;
    } catch (const std::exception& exc) {
        PyErr_SetString(PyExc_RuntimeError, exc.what());
    } catch (...) {
        PyErr_SetString(PyExc_RuntimeError, "unknown event stream MCP error");
    }
    return nullptr;
}

PyObject* py_inspect(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    int include_values = 1;
    int include_params = 1;
    static const char* keywords[] = {"path", "include_values", "include_params", nullptr};
    if (!PyArg_ParseTupleAndKeywords(
            args, kwargs, "s|pp", const_cast<char**>(keywords), &path, &include_values, &include_params))
        return nullptr;

    try {
        auto result = mcp::inspect(
            path,
            {.include_values = static_cast<bool>(include_values), .include_params = static_cast<bool>(include_params)});
        auto* dict = PyDict_New();
        auto* time_range = PyDict_New();
        auto* counts = PyDict_New();
        if (!dict || !time_range || !counts) {
            Py_XDECREF(dict);
            Py_XDECREF(time_range);
            Py_XDECREF(counts);
            return nullptr;
        }
        for (const auto& [name, value] : result.counts_by_definition) {
            if (set_new(counts, name.c_str(), PyLong_FromUnsignedLongLong(value)) < 0) {
                Py_DECREF(dict);
                Py_DECREF(time_range);
                Py_DECREF(counts);
                return nullptr;
            }
        }
        if (set_new(time_range,
                    "first",
                    result.first_time ? PyLong_FromUnsignedLongLong(*result.first_time) : Py_NewRef(Py_None))
                < 0
            || set_new(time_range,
                       "last",
                       result.last_time ? PyLong_FromUnsignedLongLong(*result.last_time) : Py_NewRef(Py_None))
                   < 0
            || set_new(dict, "path", PyUnicode_FromString(result.path.string().c_str())) < 0
            || set_new(dict, "stream_version", PyLong_FromUnsignedLong(result.stream_version)) < 0
            || set_new(dict, "definitions", py_list(result.definitions, py_definition)) < 0
            || set_new(dict, "enumerations", py_list(result.enumerations, py_enumeration)) < 0
            || set_new(dict, "parameters", py_list(result.parameters, py_parameter)) < 0
            || set_new(dict, "time_range", time_range) < 0
            || set_new(dict, "event_count", PyLong_FromUnsignedLongLong(result.event_count)) < 0
            || set_new(dict, "counts_by_definition", counts) < 0)
        {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_count(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    PyObject* events = Py_None;
    PyObject* exclude = Py_None;
    PyObject* accumulate = Py_None;
    PyObject* start = Py_None;
    PyObject* stop = Py_None;
    PyObject* interval = Py_None;
    int expand_enums = 1;
    static const char* keywords[] = {
        "path", "events", "exclude", "accumulate", "start", "stop", "interval", "expand_enums", nullptr};
    if (!PyArg_ParseTupleAndKeywords(args,
                                     kwargs,
                                     "s|OOOOOOp",
                                     const_cast<char**>(keywords),
                                     &path,
                                     &events,
                                     &exclude,
                                     &accumulate,
                                     &start,
                                     &stop,
                                     &interval,
                                     &expand_enums))
        return nullptr;

    try {
        mcp::CountOptions options;
        options.events = py_strings(events);
        options.exclude = py_strings(exclude);
        options.accumulate = py_strings(accumulate);
        options.start = py_time(start);
        options.stop = py_time(stop);
        options.interval = py_time(interval);
        options.expand_enums = expand_enums;
        auto result = mcp::count(path, options);
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "summary", py_list(result.summary, py_metric)) < 0
            || set_new(dict, "series", py_list(result.series, py_series_bucket)) < 0)
        {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_latency(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    PyObject* events = Py_None;
    const char* name = nullptr;
    const char* key = nullptr;
    const char* prefix = nullptr;
    const char* histogram = nullptr;
    int factored = 0;
    int ignore_missing = 0;
    static const char* keywords[] = {
        "path", "events", "name", "key", "prefix", "histogram", "factored", "ignore_missing", nullptr};
    if (!PyArg_ParseTupleAndKeywords(args,
                                     kwargs,
                                     "sO|zzzzpp",
                                     const_cast<char**>(keywords),
                                     &path,
                                     &events,
                                     &name,
                                     &key,
                                     &prefix,
                                     &histogram,
                                     &factored,
                                     &ignore_missing))
        return nullptr;

    try {
        mcp::LatencyOptions options;
        options.events = py_strings(events);
        if (name)
            options.name = name;
        if (key)
            options.key = key;
        if (prefix)
            options.prefix = prefix;
        if (histogram)
            options.histogram = histogram;
        options.factored = factored;
        options.ignore_missing = ignore_missing;
        auto result = mcp::latency(path, options);
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "summary", py_list(result.summary, py_metric)) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_rate(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    const char* interval = nullptr;
    PyObject* events = Py_None;
    const char* suffix = "rate";
    int factored = 0;
    static const char* keywords[] = {"path", "interval", "events", "suffix", "factored", nullptr};
    if (!PyArg_ParseTupleAndKeywords(
            args, kwargs, "ssO|sp", const_cast<char**>(keywords), &path, &interval, &events, &suffix, &factored))
        return nullptr;

    try {
        mcp::RateOptions options;
        options.interval = interval;
        options.events = py_strings(events);
        options.suffix = suffix;
        options.factored = factored;
        auto result = mcp::rate(path, options);
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "summary", py_list(result.summary, py_metric)) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_params(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    PyObject* params = Py_None;
    int all = 0;
    static const char* keywords[] = {"path", "params", "all", nullptr};
    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "s|Op", const_cast<char**>(keywords), &path, &params, &all))
        return nullptr;

    try {
        mcp::ParamsOptions options;
        options.params = py_strings(params);
        options.all = all;
        auto result = mcp::params(path, options);
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "parameters", py_list(result.parameters, py_parameter)) < 0) {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_sample(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* path = nullptr;
    PyObject* events = Py_None;
    PyObject* start = Py_None;
    PyObject* stop = Py_None;
    unsigned long long limit = 100;
    int expand_enums = 1;
    static const char* keywords[] = {"path", "events", "start", "stop", "limit", "expand_enums", nullptr};
    if (!PyArg_ParseTupleAndKeywords(args,
                                     kwargs,
                                     "s|OOOKp",
                                     const_cast<char**>(keywords),
                                     &path,
                                     &events,
                                     &start,
                                     &stop,
                                     &limit,
                                     &expand_enums))
        return nullptr;

    try {
        mcp::SampleOptions options;
        options.events = py_strings(events);
        options.start = py_time(start);
        options.stop = py_time(stop);
        options.limit = limit;
        options.expand_enums = expand_enums;
        auto result = mcp::sample(path, options);
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "events", py_list(result.events, py_event)) < 0
            || set_new(dict, "truncated", PyBool_FromLong(result.truncated)) < 0)
        {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyObject* py_cache(PyObject*, PyObject* args, PyObject* kwargs)
{
    const char* action = nullptr;
    const char* path = nullptr;
    unsigned long long memory_budget = 0;
    static const char* keywords[] = {"action", "path", "memory_budget", nullptr};
    if (!PyArg_ParseTupleAndKeywords(
            args, kwargs, "s|zK", const_cast<char**>(keywords), &action, &path, &memory_budget))
        return nullptr;

    try {
        std::string action_text{action};
        if (action_text == "clear") {
            if (path)
                mcp::clear_cache(path);
            else
                mcp::clear_cache();
        } else if (action_text == "set_memory_budget") {
            mcp::set_memory_budget(memory_budget);
        } else if (action_text != "stats") {
            throw std::runtime_error{"cache action must be stats, clear, or set_memory_budget"};
        }

        auto stats = mcp::cache_stats();
        auto* dict = PyDict_New();
        if (!dict)
            return nullptr;
        if (set_new(dict, "streams", PyLong_FromSize_t(stats.streams)) < 0
            || set_new(dict, "aggregate_results", PyLong_FromSize_t(stats.aggregate_results)) < 0
            || set_new(dict, "memory_budget_bytes", PyLong_FromSize_t(stats.memory_budget_bytes)) < 0
            || set_new(dict, "estimated_memory_bytes", PyLong_FromSize_t(stats.estimated_memory_bytes)) < 0)
        {
            Py_DECREF(dict);
            return nullptr;
        }
        return dict;
    } catch (...) {
        return translate_exception();
    }
}

PyMethodDef methods[] = {
    {"inspect", reinterpret_cast<PyCFunction>(py_inspect), METH_VARARGS | METH_KEYWORDS, "Inspect an event stream."},
    {"count", reinterpret_cast<PyCFunction>(py_count), METH_VARARGS | METH_KEYWORDS, "Count event stream records."},
    {"latency",
     reinterpret_cast<PyCFunction>(py_latency),
     METH_VARARGS | METH_KEYWORDS,
     "Measure event stream latency."},
    {"rate", reinterpret_cast<PyCFunction>(py_rate), METH_VARARGS | METH_KEYWORDS, "Measure event stream rates."},
    {"params", reinterpret_cast<PyCFunction>(py_params), METH_VARARGS | METH_KEYWORDS, "Read event stream parameters."},
    {"sample", reinterpret_cast<PyCFunction>(py_sample), METH_VARARGS | METH_KEYWORDS, "Sample event stream events."},
    {"cache", reinterpret_cast<PyCFunction>(py_cache), METH_VARARGS | METH_KEYWORDS, "Manage the event stream cache."},
    {nullptr, nullptr, 0, nullptr},
};

PyModuleDef module = {
    PyModuleDef_HEAD_INIT,
    "_event_stream_mcp",
    "C++ event stream analysis helpers for the MCP server.",
    -1,
    methods,
};

} // namespace

PyMODINIT_FUNC PyInit__event_stream_mcp()
{
    return PyModule_Create(&module);
}
