/*
 * Copyright (c) 2026, Ampere Computing LLC
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Assisted and/or generated by Codex:GPT-5
 */

#pragma once

#include "event_stream/event_stream.h"

#include <cstdint>
#include <filesystem>
#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace perf_streams::event_stream::mcp {

struct Scalar
{
    enum class Kind {
        NONE,
        BOOL,
        INT,
        UINT,
        DOUBLE,
        STRING,
        JSON,
    };

    Kind kind{Kind::NONE};
    std::variant<std::monostate, bool, int64_t, uint64_t, double, std::string> value;

    static Scalar boolean(bool value);
    static Scalar integer(int64_t value);
    static Scalar unsigned_integer(uint64_t value);
    static Scalar floating(double value);
    static Scalar string(std::string value);
    static Scalar json(std::string value);

    bool numeric() const;
    double as_double() const;
    uint64_t as_uint() const;
    std::string type_name() const;
    std::string string_value() const;
};

struct DefinitionInfo
{
    std::string kind;
    uint32_t id{0};
    std::string name;
    std::string description;
    std::optional<uint32_t> enumeration_id;
};

struct EnumerationInfo
{
    uint32_t id{0};
    std::map<int64_t, std::string> values;
};

struct ParameterInfo
{
    std::string name;
    std::string description;
    Scalar value;
};

struct EventValue
{
    uint32_t definition_id{0};
    std::string name;
    Scalar value;
    std::optional<std::string> expanded;
};

struct EventSample
{
    uint64_t id{0};
    uint32_t definition_id{0};
    std::string name;
    uint64_t time{0};
    std::vector<EventValue> values;
};

struct Metric
{
    std::string name;
    Scalar value;
};

struct SeriesBucket
{
    uint64_t start{0};
    uint64_t stop{0};
    std::vector<Metric> metrics;
};

struct InspectOptions
{
    bool include_values{true};
    bool include_params{true};
    std::optional<std::string> name_filter;
    std::optional<std::string> description_filter;
};

struct InspectResult
{
    std::filesystem::path path;
    uint32_t stream_version{0};
    std::vector<DefinitionInfo> definitions;
    std::vector<EnumerationInfo> enumerations;
    std::vector<ParameterInfo> parameters;
    std::optional<uint64_t> first_time;
    std::optional<uint64_t> last_time;
    uint64_t event_count{0};
    std::map<std::string, uint64_t> counts_by_definition;
};

struct CountOptions
{
    std::vector<std::string> events;
    std::vector<std::string> exclude;
    std::vector<std::string> accumulate;
    std::optional<uint64_t> start;
    std::optional<uint64_t> stop;
    std::optional<uint64_t> interval;
    bool expand_enums{true};
};

struct CountResult
{
    std::vector<Metric> summary;
    std::vector<SeriesBucket> series;
};

struct LatencyOptions
{
    std::vector<std::string> events;
    std::optional<std::string> name;
    std::optional<std::string> key;
    std::optional<std::string> histogram;
};

struct LatencyResult
{
    std::vector<Metric> summary;
};

struct RateOptions
{
    std::string interval;
    std::vector<std::string> events;
};

struct RateResult
{
    std::vector<Metric> summary;
};

struct ParamsOptions
{
    std::vector<std::string> params;
    std::optional<std::string> name_filter;
    std::optional<std::string> description_filter;
    bool all{false};
};

struct ParamsResult
{
    std::vector<ParameterInfo> parameters;
};

struct SampleOptions
{
    std::vector<std::string> events;
    std::optional<uint64_t> start;
    std::optional<uint64_t> stop;
    uint64_t limit{100};
    bool expand_enums{true};
};

struct SampleResult
{
    std::vector<EventSample> events;
    bool truncated{false};
};

struct CacheStats
{
    size_t streams{0};
    size_t aggregate_results{0};
    size_t memory_budget_bytes{0};
    size_t estimated_memory_bytes{0};
};

InspectResult inspect(const std::filesystem::path& path, const InspectOptions& options = {});
CountResult count(const std::filesystem::path& path, const CountOptions& options = {});
LatencyResult latency(const std::filesystem::path& path, const LatencyOptions& options);
RateResult rate(const std::filesystem::path& path, const RateOptions& options);
ParamsResult params(const std::filesystem::path& path, const ParamsOptions& options = {});
SampleResult sample(const std::filesystem::path& path, const SampleOptions& options = {});

CacheStats cache_stats();
void clear_cache();
void clear_cache(const std::filesystem::path& path);
void set_memory_budget(size_t bytes);

} // namespace perf_streams::event_stream::mcp
