// Copyright (c) 2026, Ampere Computing LLC
// SPDX-License-Identifier: BSD-3-Clause
//
// Assisted and/or generated by Codex:GPT-5

#include "event_stream/mcp/query.h"

#include "event_stream/event_stream.pb.h"
#include "event_stream/event_stream_proto.h"
#include "event_stream/event_stream_reader.h"
#include "event_stream/processor/bounds.h"
#include "event_stream/processor/utils.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fmt/format.h>
#include <functional>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <sys/stat.h>
#include <tuple>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

namespace perf_streams::event_stream::mcp {

namespace fs = std::filesystem;
namespace proto = perf_streams::event_stream_proto;
namespace processor = perf_streams::event_stream::processor;

namespace {

constexpr uint32_t stream_version = protobuf_es_version;

struct FileIdentity
{
    fs::path canonical_path;
    uintmax_t size{0};
    int64_t mtime_ns{0};
    uint64_t device{0};
    uint64_t inode{0};

    bool operator==(const FileIdentity&) const = default;
};

struct EventRow
{
    uint64_t id{0};
    uint32_t definition_id{0};
    uint64_t time{0};
    std::vector<EventValue> values;
};

struct StreamCache
{
    FileIdentity identity;
    std::map<uint32_t, DefinitionInfo> definitions;
    std::map<std::string, uint32_t> event_ids_by_name;
    std::map<std::string, uint32_t> value_ids_by_name;
    std::map<uint32_t, EnumerationInfo> enumerations;
    std::vector<ParameterInfo> parameters;
    std::vector<EventRow> events;
    std::map<std::string, std::vector<size_t>> postings_by_event_name;
    std::optional<uint64_t> first_time;
    std::optional<uint64_t> last_time;
    std::map<std::string, uint64_t> counts_by_definition;
    std::map<std::string, CountResult> count_results;
    size_t estimated_memory_bytes{0};
};

struct GlobalCache
{
    std::map<fs::path, StreamCache> streams;
    size_t memory_budget_bytes{256 * 1024 * 1024};

    static GlobalCache& instance()
    {
        static GlobalCache cache;
        return cache;
    }
};

struct FactorSpec
{
    std::string name;
    std::unique_ptr<processor::FactorBounds> bounds;
};

struct EventSelector
{
    std::string event;
    std::vector<FactorSpec> factors;
};

struct TimeCount
{
    uint64_t time{0};
    uint64_t count{0};
};

struct LatencyHist
{
    double stdev{0.0};
    uint64_t min_latency{UINT64_MAX};
    std::vector<uint64_t> max_latencies;
    std::map<uint64_t, uint64_t> latency_counts;
};

struct LatencyTracker
{
    explicit LatencyTracker(uint64_t start_time, size_t event_count)
        : time_per_event(event_count), last_event_time(start_time)
    {
    }

    std::vector<TimeCount> time_per_event;
    uint64_t last_event_time{0};
    int last_event_idx{-1};
    bool saw_start_event{false};
};

FileIdentity identify(const fs::path& path)
{
    std::error_code ec;
    auto canonical = fs::weakly_canonical(path, ec);
    if (ec)
        canonical = fs::absolute(path);

    struct stat st
    {
    };
    if (::stat(canonical.c_str(), &st) != 0)
        throw std::runtime_error{fmt::format("unable to stat event stream {}", canonical.string())};

    return {canonical,
            static_cast<uintmax_t>(st.st_size),
            static_cast<int64_t>(st.st_mtim.tv_sec) * 1'000'000'000 + st.st_mtim.tv_nsec,
            static_cast<uint64_t>(st.st_dev),
            static_cast<uint64_t>(st.st_ino)};
}

std::string definition_kind(proto::Kind kind)
{
    switch (kind) {
    case proto::EVENT:
        return "event";
    case proto::VALUE:
        return "value";
    default:
        return "unknown";
    }
}

DefinitionInfo definition_info(const proto::Definition& definition)
{
    DefinitionInfo info;
    info.kind = definition_kind(definition.kind());
    info.id = definition.id();
    info.name = definition.name();
    info.description = definition.description();
    if (definition.has_enumeration_id())
        info.enumeration_id = definition.enumeration_id();
    return info;
}

Scalar scalar_from_value(const proto::Value& value)
{
    switch (value.values_case()) {
    case proto::Value::kIntValue:
        return Scalar::integer(value.int_value());
    case proto::Value::kUintValue:
        return Scalar::unsigned_integer(value.uint_value());
    case proto::Value::kStringValue:
        return Scalar::string(value.string_value());
    default:
        return {};
    }
}

Scalar scalar_from_parameter(const proto::Parameter& parameter)
{
    switch (parameter.value_case()) {
    case proto::Parameter::kBoolValue:
        return Scalar::boolean(parameter.bool_value());
    case proto::Parameter::kIntValue:
        return Scalar::integer(parameter.int_value());
    case proto::Parameter::kUintValue:
        return Scalar::unsigned_integer(parameter.uint_value());
    case proto::Parameter::kDoubleValue:
        return Scalar::floating(parameter.double_value());
    case proto::Parameter::kStringValue:
        return Scalar::string(parameter.string_value());
    case proto::Parameter::kJsonValue:
        return Scalar::json(parameter.json_value());
    default:
        return {};
    }
}

std::optional<std::string> expanded_value(const StreamCache& stream, uint32_t definition_id, const Scalar& value)
{
    auto def = stream.definitions.find(definition_id);
    if (def == stream.definitions.end() || !def->second.enumeration_id)
        return {};

    int64_t int_value = 0;
    if (value.kind == Scalar::Kind::INT)
        int_value = std::get<int64_t>(value.value);
    else if (value.kind == Scalar::Kind::UINT)
        int_value = static_cast<int64_t>(std::get<uint64_t>(value.value));
    else
        return {};

    auto enumeration = stream.enumerations.find(*def->second.enumeration_id);
    if (enumeration == stream.enumerations.end())
        return {};

    auto enum_value = enumeration->second.values.find(int_value);
    if (enum_value == enumeration->second.values.end())
        return {};
    return enum_value->second;
}

StreamCache load_stream(const FileIdentity& identity)
{
    StreamCache stream;
    stream.identity = identity;

    EventStreamReader reader{identity.canonical_path};
    proto::Record record;
    while (reader.read(record)) {
        if (record.has_definition()) {
            auto info = definition_info(record.definition());
            auto id = info.id;
            if (info.kind == "event")
                stream.event_ids_by_name[info.name] = id;
            else if (info.kind == "value")
                stream.value_ids_by_name[info.name] = id;
            stream.definitions[id] = std::move(info);
        } else if (record.has_enumeration()) {
            EnumerationInfo info;
            info.id = record.enumeration().id();
            for (const auto& [value, name] : record.enumeration().values())
                info.values[value] = name;
            stream.enumerations[info.id] = std::move(info);
        } else if (record.has_parameter()) {
            const auto& parameter = record.parameter();
            stream.parameters.push_back({parameter.name(), parameter.description(), scalar_from_parameter(parameter)});
        } else if (record.has_event()) {
            const auto& event = record.event();
            EventRow row;
            row.id = event.id();
            row.definition_id = event.definition_id();
            row.time = event.time();

            auto event_def = stream.definitions.find(row.definition_id);
            std::string event_name = event_def == stream.definitions.end() ? fmt::format("#{}", row.definition_id)
                                                                           : event_def->second.name;

            for (const auto& value : event.values()) {
                EventValue converted;
                converted.definition_id = value.definition_id();
                if (auto def = stream.definitions.find(value.definition_id()); def != stream.definitions.end())
                    converted.name = def->second.name;
                else
                    converted.name = fmt::format("#{}", value.definition_id());

                converted.value = scalar_from_value(value);
                converted.expanded = expanded_value(stream, converted.definition_id, converted.value);
                row.values.push_back(std::move(converted));
            }

            if (!stream.first_time || row.time < *stream.first_time)
                stream.first_time = row.time;
            if (!stream.last_time || row.time > *stream.last_time)
                stream.last_time = row.time;

            stream.counts_by_definition[event_name] += 1;
            stream.postings_by_event_name[event_name].push_back(stream.events.size());
            stream.events.push_back(std::move(row));
        }
        record.Clear();
    }

    stream.estimated_memory_bytes = stream.events.size() * sizeof(EventRow);
    for (const auto& event : stream.events)
        stream.estimated_memory_bytes += event.values.size() * sizeof(EventValue);
    return stream;
}

StreamCache& get_stream(const fs::path& path)
{
    auto identity = identify(path);
    auto& cache = GlobalCache::instance();
    auto found = cache.streams.find(identity.canonical_path);
    if (found == cache.streams.end() || !(found->second.identity == identity)) {
        found = cache.streams.insert_or_assign(identity.canonical_path, load_stream(identity)).first;
    }
    return found->second;
}

std::vector<std::string> effective_events(const std::vector<std::string>& events)
{
    if (events.empty())
        return {"*"};
    return events;
}

std::regex selector_regex(const std::string& selector)
{
    return processor::regex(processor::glob_to_pattern(selector));
}

bool name_matches(const std::string& selector, const std::string& name)
{
    if (selector.empty() || selector == "*")
        return true;
    if (!processor::is_pattern(selector))
        return selector == name;
    return std::regex_match(name, selector_regex(selector));
}

EventSelector parse_selector(const std::string& spec)
{
    EventSelector selector;
    auto slash = spec.find('/');
    selector.event = slash == std::string::npos ? spec : spec.substr(0, slash);
    if (selector.event.empty())
        selector.event = "*";

    while (slash != std::string::npos) {
        auto next = spec.find('/', slash + 1);
        auto factor_text = spec.substr(slash + 1, next == std::string::npos ? next : next - slash - 1);
        if (!factor_text.empty()) {
            auto [name, bounds] = processor::FactorBounds::from_event_spec(factor_text);
            selector.factors.push_back({name, std::move(bounds)});
        }
        slash = next;
    }

    return selector;
}

std::vector<EventSelector> parse_selectors(const std::vector<std::string>& specs)
{
    std::vector<EventSelector> selectors;
    for (const auto& spec : specs)
        selectors.push_back(parse_selector(spec));
    return selectors;
}

const DefinitionInfo& event_definition(const StreamCache& stream, const EventRow& event)
{
    return stream.definitions.at(event.definition_id);
}

bool in_time_range(const EventRow& event, std::optional<uint64_t> start, std::optional<uint64_t> stop)
{
    if (start && event.time < *start)
        return false;
    if (stop && event.time >= *stop)
        return false;
    return true;
}

bool excluded(const StreamCache& stream, const EventRow& event, const std::vector<EventSelector>& exclude)
{
    const auto& name = event_definition(stream, event).name;
    return std::ranges::any_of(exclude, [&](const auto& selector) { return name_matches(selector.event, name); });
}

std::string metric_value_name(const EventValue& value, bool expand_enums)
{
    if (expand_enums && value.expanded)
        return *value.expanded;
    return value.value.string_value();
}

void add_metric(std::map<std::string, double>& metrics, const std::string& name, double value = 1.0)
{
    metrics[name] += value;
}

std::vector<Metric> metric_map_to_vector(const std::map<std::string, double>& values)
{
    std::vector<Metric> metrics;
    for (const auto& [name, value] : values) {
        auto integer_value = static_cast<uint64_t>(value);
        if (std::floor(value) == value && value >= 0.0)
            metrics.push_back({name, Scalar::unsigned_integer(integer_value)});
        else
            metrics.push_back({name, Scalar::floating(value)});
    }
    return metrics;
}

std::string count_signature(const CountOptions& options)
{
    std::stringstream ss;
    for (const auto& value : effective_events(options.events))
        ss << "e=" << value << ';';
    for (const auto& value : options.exclude)
        ss << "x=" << value << ';';
    for (const auto& value : options.accumulate)
        ss << "a=" << value << ';';
    ss << "start=" << options.start.value_or(0) << ';';
    ss << "stop=" << options.stop.value_or(UINT64_MAX) << ';';
    ss << "interval=" << options.interval.value_or(0) << ';';
    ss << "enum=" << options.expand_enums;
    return ss.str();
}

std::pair<std::string, std::string> split_accumulator(const std::string& spec)
{
    auto slash = spec.find('/');
    if (slash == std::string::npos)
        return {"*", spec};
    return {spec.substr(0, slash), spec.substr(slash + 1)};
}

void collect_count_metrics(const StreamCache& stream,
                           const CountOptions& options,
                           std::map<std::string, double>& metrics,
                           uint64_t bucket_start = 0,
                           uint64_t bucket_stop = UINT64_MAX)
{
    auto selectors = parse_selectors(effective_events(options.events));
    auto excludes = parse_selectors(options.exclude);

    for (const auto& event : stream.events) {
        if (!in_time_range(event, options.start, options.stop) || event.time < bucket_start || event.time >= bucket_stop)
            continue;
        if (excluded(stream, event, excludes))
            continue;

        const auto& event_name = event_definition(stream, event).name;
        for (const auto& selector : selectors) {
            if (!name_matches(selector.event, event_name))
                continue;

            add_metric(metrics, event_name);
            for (const auto& factor : selector.factors) {
                for (const auto& value : event.values) {
                    if (value.name != factor.name)
                        continue;
                    auto factor_value = value;
                    if (factor.bounds && factor_value.value.numeric()) {
                        auto adjusted = factor.bounds->adjust(static_cast<int64_t>(factor_value.value.as_uint()));
                        factor_value.value = Scalar::integer(adjusted);
                        factor_value.expanded.reset();
                    }
                    add_metric(metrics, fmt::format("{}/{}:{}", event_name, factor.name, metric_value_name(factor_value, options.expand_enums)));
                }
            }
        }

        for (const auto& accum_spec : options.accumulate) {
            auto [accum_event, accum_value] = split_accumulator(accum_spec);
            if (!name_matches(accum_event, event_name))
                continue;

            for (const auto& value : event.values) {
                if (value.name == accum_value && value.value.numeric())
                    add_metric(metrics, fmt::format("{}/{}", event_name, value.name), value.value.as_double());
            }
        }
    }
}

std::string build_latency_name(const std::vector<std::string>& events)
{
    if (events.empty())
        return "";

    std::stringstream name;
    auto prefix = processor::extract_prefix(events.front()).first;
    bool first = true;
    for (auto event : events) {
        if (!first) {
            name << "_";
            auto [event_prefix, event_name] = processor::extract_prefix(event);
            if (event_prefix == prefix) {
                name << event_name;
            } else {
                std::replace(event.begin(), event.end(), '.', '_');
                name << event;
            }
        } else {
            name << event;
        }
        first = false;
    }
    return name.str();
}

std::optional<uint64_t> event_key(const EventRow& event, const std::set<std::string>& key_names)
{
    for (const auto& value : event.values) {
        if (!key_names.contains(value.name))
            continue;
        if (value.value.kind == Scalar::Kind::UINT)
            return std::get<uint64_t>(value.value.value);
        if (value.value.kind == Scalar::Kind::INT)
            return static_cast<uint64_t>(std::get<int64_t>(value.value.value));
    }
    return {};
}

void record_latency(LatencyTracker& tracker, uint64_t now, int idx)
{
    if (tracker.last_event_idx >= 0) {
        auto latency = now - tracker.last_event_time;
        auto& time_count = tracker.time_per_event[tracker.last_event_idx];
        time_count.time += latency;
        time_count.count += 1;
    }

    tracker.last_event_time = now;
    tracker.last_event_idx = idx;
    if (idx == 0)
        tracker.saw_start_event = true;
}

void aggregate_latency(const LatencyTracker& tracker,
                       std::vector<TimeCount>& aggregated_info,
                       std::vector<LatencyHist>& aggregated_hist_info,
                       const std::unique_ptr<processor::FactorBounds>& histogram_bounds,
                       bool histogram)
{
    if (!tracker.saw_start_event || tracker.last_event_idx < 0)
        return;

    for (size_t idx = 0; idx < tracker.time_per_event.size(); ++idx) {
        const auto& tracker_entry = tracker.time_per_event[idx];
        auto& info = aggregated_info[idx];
        auto latency = tracker_entry.time;
        info.time += tracker_entry.time;
        info.count += tracker_entry.count;

        if (!latency)
            continue;

        auto& hist_info = aggregated_hist_info[idx];
        if (histogram) {
            auto bucket = histogram_bounds ? histogram_bounds->adjust(latency) : latency;
            ++hist_info.latency_counts[bucket];
        }

        hist_info.max_latencies.push_back(latency);
        std::sort(hist_info.max_latencies.begin(), hist_info.max_latencies.end(), std::greater<uint64_t>());
        if (hist_info.max_latencies.size() > 10)
            hist_info.max_latencies.pop_back();

        hist_info.min_latency = std::min(hist_info.min_latency, latency);
        if (info.count > 1)
            hist_info.stdev =
                std::sqrt((info.time * info.time + (info.time * info.time) / info.count) / (info.count - 1));
    }
}

void assign_latency_metrics(std::map<std::string, double>& metrics,
                            const std::string& name,
                            const TimeCount& info,
                            const LatencyHist& hist_info,
                            const std::string& histogram_metric_name,
                            bool factored_histogram,
                            const std::string& event = {})
{
    auto prefix = event.empty() ? name : fmt::format("{}.{}", name, event);
    metrics[fmt::format("{}.sum_latency", prefix)] = info.time;
    metrics[fmt::format("{}.count", prefix)] = info.count;
    metrics[fmt::format("{}.stdev", prefix)] = hist_info.stdev;

    if (!hist_info.max_latencies.empty()) {
        metrics[fmt::format("{}.max_latency", prefix)] = hist_info.max_latencies.front();
        metrics[fmt::format("{}.min_latency", prefix)] = hist_info.min_latency;
        auto max_sum = std::accumulate(hist_info.max_latencies.begin(), hist_info.max_latencies.end(), uint64_t{0});
        metrics[fmt::format("{}.max_avg_latency", prefix)] = max_sum / hist_info.max_latencies.size();
    }

    if (!histogram_metric_name.empty()) {
        for (const auto& [latency, count] : hist_info.latency_counts) {
            auto metric = factored_histogram ? fmt::format("{}/{}:{}", prefix, histogram_metric_name, latency)
                                             : fmt::format("{}.{}.{}", prefix, histogram_metric_name, latency);
            metrics[metric] = count;
        }
    }
}

std::vector<Metric> rate_for_event_interval(const StreamCache& stream, const RateOptions& options)
{
    auto trigger = options.interval;
    auto selectors = parse_selectors(effective_events(options.events));
    std::map<std::string, uint64_t> counts;
    std::map<std::string, uint64_t> previous;
    std::map<std::string, std::map<uint64_t, uint64_t>> histogram;

    auto collect_within = [&]() {
        for (const auto& [name, count] : counts) {
            auto delta = count - previous[name];
            previous[name] = count;
            ++histogram[name][delta];
        }
    };

    for (const auto& event : stream.events) {
        const auto& name = event_definition(stream, event).name;
        if (name == trigger)
            collect_within();
        for (const auto& selector : selectors) {
            if (name_matches(selector.event, name))
                ++counts[name];
        }
    }
    collect_within();

    std::map<std::string, double> metrics;
    for (const auto& [name, rates] : histogram) {
        for (const auto& [rate, count] : rates) {
            auto metric =
                options.factored ? fmt::format("{}/{}:{}", name, options.suffix, rate)
                                 : fmt::format("{}.{}.{}", name, options.suffix, rate);
            metrics[metric] = count;
        }
    }
    return metric_map_to_vector(metrics);
}

std::vector<Metric> rate_for_time_interval(const StreamCache& stream, uint64_t interval, const RateOptions& options)
{
    auto selectors = parse_selectors(effective_events(options.events));
    std::map<std::string, uint64_t> counts;
    std::map<std::string, uint64_t> previous;
    std::map<std::string, std::map<uint64_t, uint64_t>> histogram;

    auto next = stream.first_time.value_or(0) + interval;
    auto collect_within = [&]() {
        for (const auto& [name, count] : counts) {
            auto delta = count - previous[name];
            previous[name] = count;
            ++histogram[name][delta];
        }
    };

    for (const auto& event : stream.events) {
        while (event.time >= next) {
            collect_within();
            next += interval;
        }

        const auto& name = event_definition(stream, event).name;
        for (const auto& selector : selectors) {
            if (name_matches(selector.event, name))
                ++counts[name];
        }
    }
    collect_within();

    std::map<std::string, double> metrics;
    for (const auto& [name, rates] : histogram) {
        for (const auto& [rate, count] : rates) {
            auto metric =
                options.factored ? fmt::format("{}/{}:{}", name, options.suffix, rate)
                                 : fmt::format("{}.{}.{}", name, options.suffix, rate);
            metrics[metric] = count;
        }
    }
    return metric_map_to_vector(metrics);
}

bool parameter_selected(const ParameterInfo& parameter, const ParamsOptions& options)
{
    if (options.all || options.params.empty())
        return true;

    return std::ranges::any_of(options.params, [&](const auto& selector) { return name_matches(selector, parameter.name); });
}

} // namespace

Scalar Scalar::boolean(bool value)
{
    return {Kind::BOOL, value};
}

Scalar Scalar::integer(int64_t value)
{
    return {Kind::INT, value};
}

Scalar Scalar::unsigned_integer(uint64_t value)
{
    return {Kind::UINT, value};
}

Scalar Scalar::floating(double value)
{
    return {Kind::DOUBLE, value};
}

Scalar Scalar::string(std::string value)
{
    return {Kind::STRING, std::move(value)};
}

Scalar Scalar::json(std::string value)
{
    return {Kind::JSON, std::move(value)};
}

bool Scalar::numeric() const
{
    return kind == Kind::INT || kind == Kind::UINT || kind == Kind::DOUBLE || kind == Kind::BOOL;
}

double Scalar::as_double() const
{
    switch (kind) {
    case Kind::BOOL:
        return std::get<bool>(value) ? 1.0 : 0.0;
    case Kind::INT:
        return static_cast<double>(std::get<int64_t>(value));
    case Kind::UINT:
        return static_cast<double>(std::get<uint64_t>(value));
    case Kind::DOUBLE:
        return std::get<double>(value);
    default:
        throw std::runtime_error{"scalar is not numeric"};
    }
}

uint64_t Scalar::as_uint() const
{
    switch (kind) {
    case Kind::BOOL:
        return std::get<bool>(value) ? 1 : 0;
    case Kind::INT:
        return static_cast<uint64_t>(std::get<int64_t>(value));
    case Kind::UINT:
        return std::get<uint64_t>(value);
    case Kind::DOUBLE:
        return static_cast<uint64_t>(std::get<double>(value));
    default:
        throw std::runtime_error{"scalar is not numeric"};
    }
}

std::string Scalar::type_name() const
{
    switch (kind) {
    case Kind::NONE:
        return "none";
    case Kind::BOOL:
        return "bool";
    case Kind::INT:
        return "int";
    case Kind::UINT:
        return "uint";
    case Kind::DOUBLE:
        return "double";
    case Kind::STRING:
        return "string";
    case Kind::JSON:
        return "json";
    }
    return "unknown";
}

std::string Scalar::string_value() const
{
    switch (kind) {
    case Kind::NONE:
        return "";
    case Kind::BOOL:
        return std::get<bool>(value) ? "true" : "false";
    case Kind::INT:
        return fmt::format("{}", std::get<int64_t>(value));
    case Kind::UINT:
        return fmt::format("{}", std::get<uint64_t>(value));
    case Kind::DOUBLE:
        return fmt::format("{}", std::get<double>(value));
    case Kind::STRING:
    case Kind::JSON:
        return std::get<std::string>(value);
    }
    return "";
}

InspectResult inspect(const fs::path& path, const InspectOptions& options)
{
    const auto& stream = get_stream(path);
    InspectResult result;
    result.path = stream.identity.canonical_path;
    result.stream_version = stream_version;
    result.first_time = stream.first_time;
    result.last_time = stream.last_time;
    result.event_count = stream.events.size();
    result.counts_by_definition = stream.counts_by_definition;

    for (const auto& [id, definition] : stream.definitions) {
        if (options.include_values || definition.kind == "event")
            result.definitions.push_back(definition);
    }
    for (const auto& [id, enumeration] : stream.enumerations)
        result.enumerations.push_back(enumeration);
    if (options.include_params)
        result.parameters = stream.parameters;
    return result;
}

CountResult count(const fs::path& path, const CountOptions& options)
{
    auto& stream = get_stream(path);
    auto signature = count_signature(options);
    if (auto cached = stream.count_results.find(signature); cached != stream.count_results.end())
        return cached->second;

    CountResult result;
    std::map<std::string, double> summary;
    collect_count_metrics(stream, options, summary);
    result.summary = metric_map_to_vector(summary);

    if (options.interval) {
        uint64_t first = options.start.value_or(stream.first_time.value_or(0));
        uint64_t last = options.stop.value_or(stream.last_time.value_or(first));
        for (uint64_t bucket = first; bucket <= last; bucket += *options.interval) {
            auto stop = bucket + *options.interval;
            std::map<std::string, double> bucket_metrics;
            collect_count_metrics(stream, options, bucket_metrics, bucket, stop);
            if (!bucket_metrics.empty())
                result.series.push_back({bucket, stop, metric_map_to_vector(bucket_metrics)});
            if (stop <= bucket)
                break;
        }
    }

    if (stream.estimated_memory_bytes <= GlobalCache::instance().memory_budget_bytes)
        stream.count_results[signature] = result;
    return result;
}

LatencyResult latency(const fs::path& path, const LatencyOptions& options)
{
    const auto& stream = get_stream(path);
    if (options.events.empty())
        throw std::runtime_error{"latency requires at least one event"};

    std::vector<std::string> events = options.events;
    std::vector<std::string> aliases;
    aliases.reserve(events.size());
    for (auto& event : events) {
        auto pos = event.find('=');
        if (pos != std::string::npos) {
            aliases.push_back(event.substr(pos + 1));
            event = event.substr(0, pos);
        } else {
            aliases.push_back(event);
        }
    }

    std::vector<std::string> event_names;
    event_names.reserve(events.size());
    for (const auto& event : events)
        event_names.push_back(options.prefix ? fmt::format("{}.{}", *options.prefix, event) : event);

    for (const auto& event : event_names) {
        if (!stream.event_ids_by_name.contains(event) && !options.ignore_missing)
            throw std::runtime_error{fmt::format("no definition for event \"{}\"", event)};
    }

    bool tracking_transactions = !options.key;
    std::set<std::string> key_names;
    if (options.key)
        key_names.insert(options.prefix ? fmt::format("{}.{}", *options.prefix, *options.key) : *options.key);
    else
        key_names.insert("txid");

    std::string histogram_metric_name;
    std::unique_ptr<processor::FactorBounds> histogram_bounds;
    if (options.histogram)
        std::tie(histogram_metric_name, histogram_bounds) = processor::FactorBounds::from_event_spec(*options.histogram);

    std::vector<TimeCount> aggregated_info(events.size());
    std::vector<LatencyHist> aggregated_hist_info(events.size());
    std::unordered_map<uint64_t, LatencyTracker> trackers;

    auto finalize = [&](auto tracker_iter) {
        aggregate_latency(tracker_iter->second,
                          aggregated_info,
                          aggregated_hist_info,
                          histogram_bounds,
                          static_cast<bool>(options.histogram));
        trackers.erase(tracker_iter);
    };

    for (const auto& event : stream.events) {
        const auto& event_name = event_definition(stream, event).name;

        for (size_t idx = 0; idx < event_names.size(); ++idx) {
            if (event_name != event_names[idx])
                continue;

            auto key = event_key(event, key_names);
            if (!key)
                continue;

            auto [tracker_iter, _inserted] =
                trackers.try_emplace(*key, event.time, event_names.size());
            record_latency(tracker_iter->second, event.time, static_cast<int>(idx));
            if (!tracking_transactions && idx + 1 == event_names.size())
                finalize(tracker_iter);
        }

        if (tracking_transactions && event_name == "end_transaction") {
            if (auto key = event_key(event, key_names); key) {
                auto tracker_iter = trackers.find(*key);
                if (tracker_iter != trackers.end())
                    finalize(tracker_iter);
            }
        }
    }

    std::map<std::string, double> metrics;
    auto metric_name = options.name.value_or(build_latency_name(events));
    assign_latency_metrics(metrics,
                           metric_name,
                           aggregated_info.front(),
                           aggregated_hist_info.front(),
                           histogram_metric_name,
                           options.factored);

    if (events.size() > 2) {
        for (size_t idx = 0; idx < events.size() - 1; ++idx) {
            assign_latency_metrics(metrics,
                                   metric_name,
                                   aggregated_info[idx],
                                   aggregated_hist_info[idx],
                                   histogram_metric_name,
                                   options.factored,
                                   aliases[idx]);
        }
    }

    return {metric_map_to_vector(metrics)};
}

RateResult rate(const fs::path& path, const RateOptions& options)
{
    const auto& stream = get_stream(path);
    if (options.interval.empty())
        throw std::runtime_error{"rate interval is required"};

    if (processor::is_time_spec(options.interval))
        return {rate_for_time_interval(stream, processor::parse_time_spec(options.interval), options)};
    return {rate_for_event_interval(stream, options)};
}

ParamsResult params(const fs::path& path, const ParamsOptions& options)
{
    const auto& stream = get_stream(path);
    ParamsResult result;
    for (const auto& parameter : stream.parameters) {
        if (parameter_selected(parameter, options))
            result.parameters.push_back(parameter);
    }
    return result;
}

SampleResult sample(const fs::path& path, const SampleOptions& options)
{
    const auto& stream = get_stream(path);
    auto selectors = parse_selectors(effective_events(options.events));

    SampleResult result;
    for (const auto& event : stream.events) {
        if (!in_time_range(event, options.start, options.stop))
            continue;

        const auto& event_name = event_definition(stream, event).name;
        if (!std::ranges::any_of(selectors, [&](const auto& selector) { return name_matches(selector.event, event_name); }))
            continue;

        EventSample row;
        row.id = event.id;
        row.definition_id = event.definition_id;
        row.name = event_name;
        row.time = event.time;
        row.values = event.values;
        if (!options.expand_enums) {
            for (auto& value : row.values)
                value.expanded.reset();
        }
        result.events.push_back(std::move(row));
        if (result.events.size() >= options.limit) {
            result.truncated = true;
            break;
        }
    }
    return result;
}

CacheStats cache_stats()
{
    const auto& cache = GlobalCache::instance();
    CacheStats stats;
    stats.streams = cache.streams.size();
    stats.memory_budget_bytes = cache.memory_budget_bytes;
    for (const auto& [path, stream] : cache.streams) {
        stats.aggregate_results += stream.count_results.size();
        stats.estimated_memory_bytes += stream.estimated_memory_bytes;
    }
    return stats;
}

void clear_cache()
{
    GlobalCache::instance().streams.clear();
}

void clear_cache(const fs::path& path)
{
    auto identity = identify(path);
    GlobalCache::instance().streams.erase(identity.canonical_path);
}

void set_memory_budget(size_t bytes)
{
    auto& cache = GlobalCache::instance();
    cache.memory_budget_bytes = bytes;
    if (cache_stats().estimated_memory_bytes > bytes) {
        for (auto& [path, stream] : cache.streams)
            stream.count_results.clear();
    }
}

} // namespace perf_streams::event_stream::mcp
